### ISSUE TITLE
Light Weight Carryable Object Flinging

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#105]
When you stand very close to a carryable object that has low weight and pick it up, it shoots forward and out of your grip. This is easily reproduceable with the flashlight in the demo scene. I believe this is due to physics forces being placed on the object to line it up with the location it is meant to be held at.

**Comment by Phazorknight** [comment]
Thanks for the flag, but I'm marking this as won't fix, as it's not an actual issue.

The Carryable Component has all parameters exposed to change this behavior to what's preferred.
I'll tweak the parameters a bit in the next commit, so the flashlight doesn't get flung, but these settings will always depend
quite a bit on the object, mostly it's shape and center transform.
Tweaking the Carry Distance Offset is usually all that's needed, but also reducing the Carrying Velocity multiplier can help.

Here's what I set it to that "feels good" in my book.
![image](https://github.com/Phazorknight/Cogito/assets/70389309/ed32e820-307d-4756-8df2-a26f34672479)

**Comment by ac-arcana** [comment]
Absolutely makes sense to me. It just a case of adjusting the flashlight values in the demo as you said :)
