### ISSUE TITLE
Dropping stacks will drop the full quantity at once, but only one can be picked back up.

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#107]
Pick up a stack of anything in a demo scene. Then click it and click out of inventory to drop it. There is now only one on the ground, but your full stack is gone. When you pick up the one item, you do not get the full quantity back.

**Comment by Phazorknight** [comment]
Thanks for catching this!
Should hopefully be fixed in https://github.com/Phazorknight/Cogito/commit/e242fd2ee9e5a2dee70599e6d8f32519dc416046 , please give it a try.

**Comment by ac-arcana** [comment]
Awesome, its fixed.
