### ISSUE TITLE
Carryable Object Destruction Results in Error

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#108]
If you are carrying a carryable and it is destroyed while you are carrying it, then when you next press the carry input there is an error.

**Comment by Phazorknight** [comment]
Thanks for flagging this.
Have a pretty good idea on what causes this and how to fix it, so should be able to get this done today.

**Comment by Phazorknight** [comment]
Please check https://github.com/Phazorknight/Cogito/commit/003d035fe75bc7a915e7a6d13353f3850b646a39.

This adds a check to the Player Interaction component to see if the carryable object reference is still valid, and if not clears it.
You should no longer get crashes, but it's possible that you have to press an interact button first before the reference is updated. Will see if I can somehow make it cleaner, but if it works for you, I'd consider this resolved.

**Comment by ac-arcana** [comment]
Solved!
