### ISSUE TITLE
Mouse Inverted, up is down, down is up.

### ISSUE THREAD

**Issue by CappyTech** [Phazorknight/Cogito#122]
Mouse Inverted, up is down, down is up.

I don't know what else to say, up is down and down is up on a mouse.

Version: **BETA 202401.13**
Runs on Godot **4.2.1 stable**

**Comment by Phazorknight** [comment]
- Get latest version from here on GitHub.
- In Play mode, in the options meneu, change "Invert Y" to your liking (I have it on by default as it's my preference)

**Comment by CappyTech** [comment]
Ah, didn't notice that, thanks.

**Comment by Phazorknight** [comment]
Closing.

**Comment by Phazorknight** [comment]
We're looking into making default settings a resource.

> https://github.com/Phazorknight/Cogito/discussions/486
