### ISSUE TITLE
Can't click on main menu

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#126]
I can use a controller to navigate the menu,
but the mouse no longer highlights or clicks anything on the main menu.

**Comment by ac-arcana** [comment]
Not sure why this is happening. I tried changing "Mouse Filter" on a few of the panels in the upper hierarchy from Stop to Pass, but that doesn't seem to fix it...

**Comment by Phazorknight** [comment]
Oops! Sorry about that.
This should be fixed now in https://github.com/Phazorknight/Cogito/commit/10befee1207ecc7f134d115fdbab173c41289141
