### ISSUE TITLE
Creating new scenes with player, player_hud and PauseMenu should be documented better

### ISSUE THREAD

**Issue by pcbeard** [Phazorknight/Cogito#13]
Per ReadMe.md:

> All signals needed get hooked up via code, so this should work without any extra signal setup.
> PauseMenu and MainMenu Scenes contain SceneSwitchers that need paths to the *.tscn files to work.
>Also be aware of node order for Player_HUD and PauseMenu. Player_HUD node should be above PauseMenu node, so PauseMenu is "on top". 

I've noticed that when I build a new scene, I also need to connect by-hand the `PauseMenu.resume()` signal to player._on_pause_menu_resume(). We should document this, or if possible, connect the signal automatically. The symptom when you don't connect the signal is that the player doesn't start moving again when you hit the Resume button.

**Comment by Phazorknight** [comment]
Thanks for flagging this!
I've removed the signal hookup from the scene and now let the player.gd connect to this via code.
So this should be fixed in BETA 202401.5
