### ISSUE TITLE
Create Wieldables template and node type

### ISSUE THREAD

**Issue by GreenCloversGames** [Phazorknight/Cogito#130]
Hi all, 

Having used this awesome add on for a project, I had an issue when I wanted to create my own Wieldable. I was able to resolve these and get the Wieldable working but I could see some ways to improve the pipeline for creating a game. 

Firstly, as a Wieldable object needs a certain number of methods, I think there should be a script template in the project.  You can see how to do this here - [https://docs.godotengine.org/en/stable/tutorials/scripting/creating_script_templates.html]()

Secondly, to make it easier to implement and to update, I think there should be a Wieldable node that can be used as a base. 

Thoughts?

**Comment by Phazorknight** [comment]
Hey, thanks so much for your feedback.

I actually wasn't aware of script templates, so thanks for pointing those out! Creating a wieldable script template seems like the perfect use case, I'll look into adding that.

**Comment by ksjfhor** [comment]
I would appreciate this very much as I am struggeling to implement a dart board in the break room right now :)
