### ISSUE TITLE
Error with slide audio when sliding -> jumping -> landing

### ISSUE THREAD

**Issue by Phazorknight** [Phazorknight/Cogito#131]
@ac-arcana 

I've encountered this issue and was able to replicate it reliably:

When I sprint, slide and jump while sliding, the slide sound keeps playing (should probably stop as soon as the player is in the air).
If the sound is still playing by the time I land, the game errors:

```
player.gd: line 764: slide_audio_player.stop() - Cannot call method `stop` on a previously freed instance.
```

**Comment by ac-arcana** [comment]
I'll look at it tomorrow :)

**Comment by Phazorknight** [comment]
Sounds good, no rush!

**Comment by Phazorknight** [comment]
Sweet, thanks for this fix!
Closing this now.
