### ISSUE TITLE
Weapon wielding status not properly reset after death

### ISSUE THREAD

**Issue by samaritan-sw** [Phazorknight/Cogito#134]
After dying with a weapon in hand, you respawn empty-handed. If you then pick up a weapon and try to wield it with a hotkey, nothing will happen on screen but the log will say "Putting away [weapon]". You have to push the hotkey a second time to get the weapon to equip properly.

Repro steps:
- Run COGITO_01_Demo
- Pick up the foam pistol, equip it, then fall to your death
- When you respawn, pick up the foam pistol, then press the equip key (nothing happens). Press it again to equip the weapon. 

I'm not too familiar with Cogito yet, but I suspect the issue is with the is_being_wielded property in WieldableItemPD.gd persisting after death - maybe it should always be set to false on startup, or at least check for a wieldable item in the default slot before setting itself to true?

**Comment by Phazorknight** [comment]
Thanks for flagging this!
Will look into it, but what you mentioned is probably on the right track.

**Comment by Phazorknight** [comment]
Could you take a look at https://github.com/Phazorknight/Cogito/commit/b40272a6831969a808899cf128e487cadea33ed9 and see if that fixes this for you?

**Comment by samaritan-sw** [comment]
Yep, that seems to have done it! 👍

**Comment by Phazorknight** [comment]
Sweet, closing this!
