### ISSUE TITLE
Crash on repeated scene transitions

### ISSUE THREAD

**Issue by samaritan-sw** [Phazorknight/Cogito#138]
A crash happens after repeatedly loading demo scene 4 from scene 5.

Repro steps:

- Simply load Cogito_04_Demo or Cogito_05_Demo and walk between the two scenes, triggering the loading screen. After loading scene 4 two or three times that way, Cogito will crash with the following error:

![image](https://github.com/Phazorknight/Cogito/assets/59507949/3603c47a-7a0a-44d9-bf0d-a45c7e9ee06a)

The issue seems to be that Cogito is trying to locate a QuestUpdaterA node parented to a Rigidbody that doesn't seem to exist when looked at in the remote inspector:

![image](https://github.com/Phazorknight/Cogito/assets/59507949/4f87a478-0acc-46a6-b9b3-1e1d6028be18)

This happens when trying to load state data, so probably an issue with the way the data is saved - or perhaps with the way that particular node is set up? I couldn't get this crash to happen by transitioning between demo scenes 1 and 2, and when transitioning between scenes 4 and 5, scene 4 is always the issue.

**Comment by Phazorknight** [comment]
Thanks for flagging this! 
Could you give https://github.com/Phazorknight/Cogito/commit/65be57d0ef58be1db46565f29b9081c126a59fbc a try and see if it solves your issue?


Also, really appreciate the reproduction steps, was able to narrow down the issue quickly thanks to this.
The culprit wasn't a particular node, but the fact that QuestUpdater script was set up to save its state to the scene state, which is actually unnecessary.
