### ISSUE TITLE
Use cylinder for collider instead of box

### ISSUE THREAD

**Issue by brian-holsters** [Phazorknight/Cogito#155]
The main reason for Cylinder over box shape is maneuvering near corners, just walking around I've had quite a bit of trouble getting stuck at corners, this is especially noticeable at doors, personally I normally prefer capsules for easy slope handling as well, but it seems to not work with the stair system, whereas the cylinder does work flawlessly.

I do not know however if there are any other systems in place that require the player collider to be a box...

**Comment by Phazorknight** [comment]
I agree with the getting caught on corners part.
I still had the Box colliders from the initial implementation for the stair system, which was based on them.
As you said, the stair system required collider shapes that have an edge on the floor to properly detect steps, hence capsules aren't suitable.

If you gave Cylinder colliders a go and found them to work well, I'd say this would be a worthwhile change.
Feel free to put in a PR.
