### ISSUE TITLE
Issues with Doors

### ISSUE THREAD

**Issue by samaritan-sw** [Phazorknight/Cogito#156]
These are two separate issues with doors so I think it's worth grouping them together. 

**Cogito and Godot Engine Version:**
Godot 4.2.1
Cogito latest

First issue:

**Description:**
When a sliding door starts the scene as "Is Open", the door behaves as if it were closed.

**Reproduction steps:**
- Load lab scene
- Open the door then sprint to the scene transition (or just set the timer to longer than 2 seconds - basically the door needs to be open when you leave the scene)
- Re-enter scene 5 - the door appears closed but the "Close" prompt is displayed, indicating that it should behave as open.
- Interact with the door - the closing sound is played and the prompt is updated to "Open".
- Also works with the 0451 door in scene 1. Open the door, go into the transition corridor, and come back - the door appears closed but its true state is open.

**Expected behavior:**
A door that is open upon leaving a scene should behave as open when you re-enter the scene. 

**Screenshots:**
![image](https://github.com/Phazorknight/Cogito/assets/59507949/d0ac8c5f-5ec3-4d1e-850a-defd91b235db)

This one is probably to do with how sliding doors are saved? This doesn't affect regular doors, whether on a timer or not.

I've also noticed that door timer states aren't saved, therefore timers are disabled when you re-enter a scene, even if the door that you left open upon exiting the scene was on a timer. That means that when doors behaves correctly, they can remain open indefinitely until interacted with again.

Second issue:

**Description:**
Doors on a timer don't update their interaction prompt upon closing if the player keeps looking at the door while it is closing.

**Reproduction steps:**
- Load lab scene
- Look at the hinge of the door (see screenshot) and press the interact key to open it. The "Close" prompt appears correctly. However, upon the door timer timing out, the door closes and the "Close" text is still displayed instead of the "Open" text.
- Look away from the door then look at it again - the "Open" prompt is correctly shown. 

**Expected behavior:**
A closed or closing door displays its "Interaction Text When Closed" prompt at all times.

**Screenshots:**
![image](https://github.com/Phazorknight/Cogito/assets/59507949/8a98c370-8bd7-4650-9f84-f01c00dc728b)

I've identified the cause but am not sure how to solve the issue. Basically, an object's updated state is only signalled out upon the player looking at the object or interacting with it. Objects interacting with themselves (in the case of doors, via a timer) currently cannot update their associated interaction prompts if the player keeps looking at the object while it's changing states.

**Comment by Phazorknight** [comment]
Thanks for flagging this!
I think I have a decent idea on how to fix it, will look into it today.

**Comment by Phazorknight** [comment]
> Doors on a timer don't update their interaction prompt upon closing if the player keeps looking at the door while it is closing.

This should be fixed now in https://github.com/Phazorknight/Cogito/commit/ce3c4d90300c1ba9536233b22abfed0b7537afe2
The door forces an update to the interaction prompt when closing.

> When a sliding door starts the scene as "Is Open", the door behaves as if it were closed.

I was not able to replicate this issue on my end. Demo Scene 01, i entered the code to open the sliding door, then went into the scene transition corridor to switch scenes. When coming back, the sliding door was still open.
Same with the sliding door in Demo Scene 05 Laboratory.

> I've also noticed that door timer states aren't saved

Yeah, this is still an issue. Gonna look into how to solve this. Saving the timer time left seems a bit overkill, as the overall sentiment of this function is to just keep doors closed, so I might just override the door state to be closed or something.

**Comment by samaritan-sw** [comment]
Thanks for this! Looks like you killed two birds with one stone here, as I now can't reproduce either issue. 😄 

Regarding timers, your solution seems like a perfect compromise, as I doubt a dev would want to set up a door with a timer that persists across areas with loading screens in between. 😅

**Comment by Phazorknight** [comment]
Doors set to close automatically after a certain time will now always start as closed when a scene is entered.

See https://github.com/Phazorknight/Cogito/commit/76da19419bfcbe58d21cabfab23186d0e756dc13

With this I consider this issue as resolved. Please (re)open if there are still problems.
