### ISSUE TITLE
Bi-directional door animations

### ISSUE THREAD

**Issue by pcbeard** [Phazorknight/Cogito#16]
I've been working with these [house assets](https://loafbrr.itch.io/houses-and-props) and realized that the default animations it uses which open a door when a player character is nearby are a bit awkward to use when the doors open toward the character. Toward that end, I've prototyped a solution that I would love to see incorporated into Cogito, if possible. You can see what it looks like in [this mastodon post](https://sfba.social/@pcbeard/111712548072890686).

The main idea would be to have the door swing inward if approached from one side, and outward from the other. I implemented this by adding another Area3D to determine which side the of the door the player is approaching from, and managing a simple state machine to run the animations.

**Comment by pcbeard** [comment]
Here's the GDScript code I wrote to implement this logic:

```GDScript
extends Node3D

@onready var animation = $AnimationPlayer

enum { CLOSED, CLOSING, OPENING, OPEN }
var door_state = CLOSED
var in_outside_area = false
var in_inside_area = false
var closing_animation = ""

func check_door_state():
	match door_state:
		CLOSED:
			if in_outside_area:
				door_state = OPENING
				animation.play("open_inward")
				closing_animation = "open_inward"
			elif in_inside_area:
				door_state = OPENING
				animation.play("open_outward")
				closing_animation = "open_outward"
		OPENING:
			pass
		CLOSING:
			pass
		OPEN:
			if !in_outside_area and !in_inside_area:
				door_state = CLOSING
				animation.play_backwards(closing_animation)

func _on_animation_player_animation_finished(anim_name):
	match door_state:
		OPENING:
			door_state = OPEN
		CLOSING:
			door_state = CLOSED
	check_door_state()

func _on_outside_area_3d_body_entered(body):
	if body is CharacterBody3D:
		in_outside_area = true
		check_door_state()

func _on_outside_area_3d_body_exited(body):
	if body is CharacterBody3D:
		in_outside_area = false
		check_door_state()

func _on_inside_area_3d_body_entered(body):
	if body is CharacterBody3D:
		in_inside_area = true
		check_door_state()
		
func _on_inside_area_3d_body_exited(body):
	if body is CharacterBody3D:
		in_inside_area = false
		check_door_state()
```

**Comment by Phazorknight** [comment]
Thanks for this.
Your script is based on how the doors work within that asset pack and the included script. As this is a different approach on how COGITO is set up, I'm not going to include it in the repo.

That being said: I understand the request was able to add this functionality to COGITO in a different way.
I've created a "door setter zone" script, that when attached to a zone can override a door's settings when the player enters said zone.
Putting on of these on each side of a door can create the behaviour you described.

You can see how it works here:

https://github.com/Phazorknight/Cogito/assets/70389309/575ed88f-fd45-4296-a057-5ac3abe3406b

I'll include this script in the next update, but if you want to give it a try earlier, here it is (with automatic signal hookup):

**door_setter_zone.gd**
```
extends Area3D

## Reference to the door that will get upated
@export var door_to_set : NodePath
## Setting the new open rotation position in degrees.
@export var new_open_rotation_deg : float
## Check this is the door is changing transform position instead of rotation
@export var is_sliding : bool
## The new open position transform coordinates
@export var new_open_pos : Vector3
## Check this is the door is animation based
@export var is_using_animations : bool
## Name of the new opening animation. This has to exist in the door's animation player to work.
@export var new_opening_animation : String

func _ready():
	body_entered.connect(_on_body_entered)
	
	
func _on_body_entered(body: Node3D):
	if !body.is_in_group("Player"):
		return
		
	if door_to_set != null:
		var door = get_node(door_to_set)
		if is_sliding:
			door.open_position = new_open_pos
		elif is_using_animations:
			door.opening_animation = new_opening_animation
		else:
			door.open_rotation_deg = new_open_rotation_deg
	
```

**Comment by pcbeard** [comment]
Looks great. I do like the option to have automatic doors too.

**Comment by pcbeard** [comment]
Thanks for making this happen!
