### ISSUE TITLE
Opened doors break upon scene transition

### ISSUE THREAD

**Issue by aronand** [Phazorknight/Cogito#181]
**Cogito and Godot Engine Version:**
Godot: 4.2.1
Cogito: 6d9f37e

**Description:**
Opened doors visually break if a scene is switched. This seems to impact all opened doors in one way or another.

**Reproduction steps:**
1. Open all the doors in the first level of demo map
2. Move to the laboratory scene
3. Move back to the initial scene
4. Observe that the doors now exhibit the following oddities: opened door looks closed, opened door's position is slightly wrong, or the opened doors position is so wrong, that it no longer shows up in the map.

**Expected behavior:**
The doors should retain their position if their state has been altered.

**Screenshots:**
![closed_open_door](https://github.com/Phazorknight/Cogito/assets/71503746/7241cda1-8484-4103-b19d-5f5a8888e940)
*Door looks visually closed, but state is open*

![cupboard_doors](https://github.com/Phazorknight/Cogito/assets/71503746/30b0c345-38d3-41d0-98f9-354e15a51fb0)
*Doors look closed, but are also positioned wrong*

![vanished_door](https://github.com/Phazorknight/Cogito/assets/71503746/f1bfd6f4-55cd-46a9-879b-e84f0f98451f)
*Door has vanished from the scene, most likely somewhere outside the level*

**Comment by Phazorknight** [comment]
Thanks for flagging this: was able to reproduce and am looking into it.

**Comment by Phazorknight** [comment]
Ok, this should be fixed in https://github.com/Phazorknight/Cogito/commit/2ee85030bba5f0e76bc18d432d0a00ed5184f966

When I implemented the state loader for the sliding door that can close automatically, I made that the default for ALL doors if they were open. This update fixes this and implements two methods that improve readability to set door states more easily.

**Comment by aronand** [comment]
Doors now seem to function as intended 👍 the note still disappears however, in both original and new test map.

**Comment by Phazorknight** [comment]
@aronand yeah, there's actually something weird going one with Cogito Objects that are based on StaticBody3Ds. Will make a separate issue about it.
