### ISSUE TITLE
InteractionRaycast doesnt appear to be working at all

### ISSUE THREAD

**Issue by PeterD23** [Phazorknight/Cogito#185]
**Cogito and Godot Engine Version:**
4.2.1.stable.mono

**Description:**
Player is unable to interact with any objects, looks to be an issue with the InteractionRaycast since running the project was throwing a "cannot add null value to add_exception_rid()" on player._ready()
This appeared to happen after updating branch from commit [6d9f37e1a7fb0eee6d3a7d3399f5f4e00f9be1c1](https://github.com/Phazorknight/Cogito/tree/6d9f37e1a7fb0eee6d3a7d3399f5f4e00f9be1c1)

**Reproduction steps:**
1. Run the project with the latest main commit
2. Note the add_exception_rid() error
3. Stop the project, attach the interaction_raycast.gd script to the Player scene InteractionRaycast
4. Rerun the project, note error no longer appears, but nothing is interactable

**Expected behavior:**
Items should be interactable

**Screenshots:**
![image](https://github.com/Phazorknight/Cogito/assets/10536628/cdb530d8-fdd9-49c5-9ed2-b16778ff54dc)

**Comment by aronand** [comment]
I'm unable to reproduce this from a clean pull. Can you paste the error you're seeing as well?

I'm only getting the following warnings:
![image](https://github.com/Phazorknight/Cogito/assets/71503746/bd50e1fe-a5b9-49e8-bf71-0096ab5c2a91)

Regarding step three, they raycast should have the script assigned to it already 🤔
https://github.com/Phazorknight/Cogito/blob/main/COGITO/PrefabScenes/player.tscn#L99

**Comment by aronand** [comment]
Oh nevermind, saw the error at the top. That's a really weird one though, not sure why get_rid() would be returning null from the player there.

**Comment by PeterD23** [comment]
When I pulled over the files I chose "reload" instead of "resave" because I assumed that would have updated the files the newly copied ones but is that correct?

**Comment by PeterD23** [comment]
I wiped the whole folder and started again after a failed attempt to do some refactoring and now it seems to work. I'm guessing Godot cached some files which ended up causing issues.
