### ISSUE TITLE
Re-bindable Inputs

### ISSUE THREAD

**Issue by Phazorknight** [Phazorknight/Cogito#19]
Since Nathan Hoad's input helper includes functions to rebind inputs on runtime, it should be relatively straight foward to create a "Controls" menu in the options that lists all current key bindings and lets the user rebind them as needed.

Please let me know if someone would be up to tackle this, as I'd love to focus more getting scene persistence working.
Thanks in advance!

**Comment by Jealousmango** [comment]
Hi! I'd love to take a shot at implementing rebinding keys if this issue is still valid.

**Comment by Phazorknight** [comment]
Yes, this is still valid. Would be awesome if you could take a shot.
Please make sure you pull from the latest `/main/` as I've added another input map action on that one: `interact2`.

**Comment by Jealousmango** [comment]
Wanted to drop a quick update on where I'm at on this issue!

I've setup a placeholder Controls menu option within the existing Options menu and I'm populating that menu with the input map. I've also started hooking up the data for things like the button and key input text. Once that's working remapping the input should be straightforward. I'm hoping to have some free time this week to continue making progress.

![image](https://github.com/Phazorknight/Cogito/assets/12888015/61b6256f-1b0e-4e3e-84c0-f760e9d409e1)

**Comment by Phazorknight** [comment]
Looks promising! Thanks for the update.

**Comment by generrosity** [comment]
that looks amazing! 

Just incase its useful, DashNothing did a clever [remapping algorythm](https://www.youtube.com/watch?v=ZDPM45cHHlI), and they used a dictionary to translate the ui_key elements 👍

I've also just proposed tweaking the Options page to have the title and 'back' buttons always visible 😅 just baby changes from me currently

**Comment by JouBqa** [comment]
Good job. Can you also add toggle crouch/sprint?

**Comment by Phazorknight** [comment]
> Good job. Can you also add toggle crouch/sprint?

This is an addition for #55 / Gameplay options. Not for rebindable inputs.

> DashNothing did a clever [remapping algorythm](https://www.youtube.com/watch?v=ZDPM45cHHlI)
I can't confirm how @Jealousmango approaches it, but COGITO comes with Nathan Hoad's InputHelper, which already includes functions for input remapping, so I think it's currently just about implementation.

**Comment by Phazorknight** [comment]
Is there a simple way to exclude the godot default inputs? AFAIK they're never explicitly used in the scripts besides the default UI navigation and it's pretty rare that someone would want to rebind these.

Alterantively there might be away to replace the input map action names with readable ones with a simple dictionary or something, with falling back to the default string name if no entry is found. 🤔

**Comment by Jealousmango** [comment]
> Is there a simple way to exclude the godot default inputs? AFAIK they're never explicitly used in the scripts besides the default UI navigation and it's pretty rare that someone would want to rebind these.
> 
> Alterantively there might be away to replace the input map action names with readable ones with a simple dictionary or something, with falling back to the default string name if no entry is found. 🤔

I wasn't able to find a simple way to exclude the default inputs, but I haven't dug too deeply yet. One possible route would be creating a map of blacklisted actions and including all of the Godot default actions.

I think you're right about defining a dictionary for more readable names and falling back on the default string if one isn't provided. I'll be sure to include that. Thanks for the feedback!

**Comment by FailSpy** [comment]
>  I wasn't able to find a simple way to exclude the default inputs, but I haven't dug too deeply yet.

I've done some investigating in the past on this. And as far as I could find, there isn't a method available from GDScript that can tell you whether an Input mapping is built-in or not. There is, tantalisingly, in the Godot source code a function called 'get_builtins'
https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/core/input/input_map.cpp#L382
I was completely unable to find any reference to this that's accessible via GDScript.
If you're sufficiently motivated, you might be able to use GDNative to hook into that directly.

Personally wasn't willing to go that far, so I came up with this hack-y Resource instead (edited slightly to make more sense in context):
```gdscript
@tool
extends Resource
class_name RebindableActions

@export var inputs : Array[String]
static var custom_actions : Array[String]

func _init():
	inputs = get_actions().duplicate()
	ProjectSettings.property_list_changed.connect(_refresh)

static func _refresh():
	custom_actions = []
	var was_input = false
	var loaded_defaults = false
	for setting in ProjectSettings.get_property_list():
		var is_input = setting.name.begins_with('input/')
		if was_input and not is_input:
			loaded_defaults = true
		elif is_input and loaded_defaults:
			custom_actions.push_back(setting.name.split('/')[-1])
		was_input = is_input

func get_actions():
	if custom_actions:
		return custom_actions
	_refresh()
	return custom_actions

func _property_can_revert(property):
	if property == 'inputs':
		return get_actions() != inputs

func _property_get_revert(property):
	if property == 'inputs':
		return get_actions().duplicate()
```

This works because ProjectSettings will provide you the property list *in the order it was loaded*. 
So it loads the built-in project settings *first*, and then loads any user configured project settings. Even if you add/remove inputs from the built-in actions, all built-in actions will stay bunched together. And of course, you can reverse `_refresh()`s behaviour to get all builtin actions.

This will work on export as well. 

If you would rather just a full list to be updated of the built-in actions manually, you can find them earlier on in that same Godot source code:
https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/core/input/input_map.cpp#L292

RebindableActions can then serve as your "whitelist" of inputs. There's nothing stopping a user from adding built-in inputs if that's desireable, or removing custom ones.

**Comment by Jealousmango** [comment]
> > I wasn't able to find a simple way to exclude the default inputs, but I haven't dug too deeply yet.
> 
> I've done some investigating in the past on this. And as far as I could find, there isn't a method available from GDScript that can tell you whether an Input mapping is built-in or not. There is, tantalisingly, in the Godot source code a function called 'get_builtins' https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/core/input/input_map.cpp#L382 I was completely unable to find any reference to this that's accessible via GDScript. If you're sufficiently motivated, you might be able to use GDNative to hook into that directly.
> 
> Personally wasn't willing to go that far, so I came up with this hack-y Resource instead (edited slightly to make more sense in context):
> 
> ```gdscript
> @tool
> extends Resource
> class_name RebindableActions
> 
> @export var inputs : Array[String]
> static var custom_actions : Array[String]
> 
> func _init():
> 	inputs = get_actions().duplicate()
> 	ProjectSettings.property_list_changed.connect(_refresh)
> 
> static func _refresh():
> 	custom_actions = []
> 	var was_input = false
> 	var loaded_defaults = false
> 	for setting in ProjectSettings.get_property_list():
> 		var is_input = setting.name.begins_with('input/')
> 		if was_input and not is_input:
> 			loaded_defaults = true
> 		elif is_input and loaded_defaults:
> 			custom_actions.push_back(setting.name.split('/')[-1])
> 		was_input = is_input
> 
> func get_actions():
> 	if custom_actions:
> 		return custom_actions
> 	_refresh()
> 	return custom_actions
> 
> func _property_can_revert(property):
> 	if property == 'inputs':
> 		return get_actions() != inputs
> 
> func _property_get_revert(property):
> 	if property == 'inputs':
> 		return get_actions().duplicate()
> ```
> 
> This works because ProjectSettings will provide you the property list _in the order it was loaded_. So it loads the built-in project settings _first_, and then loads any user configured project settings. Even if you add/remove inputs from the built-in actions, all built-in actions will stay bunched together. And of course, you can reverse `_refresh()`s behaviour to get all builtin actions.
> 
> This will work on export as well.
> 
> If you would rather just a full list to be updated of the built-in actions manually, you can find them earlier on in that same Godot source code: https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/core/input/input_map.cpp#L292
> 
> RebindableActions can then serve as your "whitelist" of inputs. There's nothing stopping a user from adding built-in inputs if that's desireable, or removing custom ones.
> 
> You will need to add some behaviour to _refresh() that can detect and add _new_ Inputs on project settings changes to auto-import those, at the very least for any RebindableActions that return false on "can_revert"

When I worked on this I just _knew_ there had to be some way to get those actions from the Godot source code, but being fairly new to Godot myself I thought it would faster to just type them all out myself 😅. This is super helpful info and I'm happy that my hunch was correct! Next time I'll definitely go hunting in the source code for this type of thing.

Currently I'm filtering all of the built-ins with a defined map. I'll probably put a pin in the filtering part for now but I could revisit this before opening the PR if your auto-loading method feels like a better way to handle loading the built-ins.

Thanks for all the help!

**Comment by Jealousmango** [comment]
Another quick update about my progress!

I've filtered out all of the built-in action names and have also implemented the discussed "friendly" names mapping for action names. If no friendly name is added to the map the label text will fall back to the default name.

I also have a simple rebind menu that pops up when the rebind button is clicked with data for the relevant action piped into the rebind menu. I'm listening for input on that menu and rebinding the associated action to the new input. Currently working through the saving dialog and logic. 

Once that's done I'll clean up the button labels based on the detected device. For Joypads I'd really love to dynamically change the button label to an icon for the correct device, but that would require importing icons for each type of Joypad I think? I'd welcome any feedback on this!

When I prepare this PR, should I open that against the new tabbed menu design from #55? For testing my current setup is just a Controls button on the main menu but I can migrate what I have into the tabs redesign if that makes sense.

![image](https://github.com/Phazorknight/Cogito/assets/12888015/731943fa-8e2c-4fe6-b734-655a55b69a2b)

**Comment by Phazorknight** [comment]
Due to inactivity, I've started working on this on my end. I've added a very early implementation in https://github.com/Phazorknight/Cogito/commit/987380123db3a478a29f6b04b13f27edba739c09
Please see the notes of that commit for details.

**Comment by Phazorknight** [comment]
Closing this issue as this seems to be working as intended now. Please open a new issue if you run into any problems.
