### ISSUE TITLE
Is steam deck function error

### ISSUE THREAD

**Issue by theclaytondab** [Phazorknight/Cogito#20]
It says it cant get_rendering_name on null
on get_rendering_device
![Screenshot 2024-01-10 3 48 47 PM](https://github.com/Phazorknight/Cogito/assets/115123152/a4ab6107-e457-4176-8878-3a674690c092)
![Screenshot 2024-01-10 3 48 36 PM](https://github.com/Phazorknight/Cogito/assets/115123152/89dae961-0363-49ec-ada2-e159769f4778)
*on compatibility mode and on chromebook*

**Comment by Phazorknight** [comment]
Never had an issue with this, but seems like there's cases where get_rendering_device returns null.
I'll try to add a null check on this on the next update, but in the meantime you should be able to fix this by adding these lines to the _is_steam_deck() function:

```
func _is_steam_deck() -> bool:
  if RenderingServer.get_rendering_device() == null:
		print("No rendering device detected.")
		return false
```

**Comment by theclaytondab** [comment]
That fix worked
