### ISSUE TITLE
Character gets stuck on stairs

### ISSUE THREAD

**Issue by PeterD23** [Phazorknight/Cogito#207]
**Cogito and Godot Engine Version:**
Cogito master, Godot 4.2.1.stable.mono

**Description:**
I get stuck on stairs and become unable to do anything. Happens every time on Cogito_4_Laboratory, with the steps leading up to the box.

**Reproduction steps:**
Load up Cogito_4_Laboratory
Try and walk up the steps to the box

**Expected behavior:**
Player does not get stuck

**Comment by Phazorknight** [comment]
Hey, yeah I've noticed that the generated collision shapes on some of these seemingly simple meshes don't always play nice.

Please check https://github.com/Phazorknight/Cogito/commit/3c78fa7a69fce2ccab32ac099a719a2db114c926

- I've updated the Player scenes collision shape back to be a box collider. This overall seems to be the most "stable" in terms of getting stuck etc.

- I've also manually created box colliders for those corner stairs in the Lab scene, which should also help with collision issues.

**Comment by PeterD23** [comment]
So I've been prototyping some level design with Trenchbroom and Func_Godot for my use case, and after switching to the box it still seems like theres weird issues, like getting stuck on my pyramid unless I'm looking up for some reason? Theres also one singular step in my spiral staircase that I cannot figure out why I can't traverse it except right at one of the edges. The problem goes away if I set the slope angle to 90 degrees but it makes ramp traversal look weird
(apologies for the video quality, had to handbrake it down to less than 10 mb)
https://github.com/Phazorknight/Cogito/assets/10536628/667a01cc-3bd5-4a84-aaaf-8eba65c46f0f

**Comment by Phazorknight** [comment]
Yeah, this is a bit tricky. 
The stair handling isn't perfect and there's lots of weird edge cases like this.

I'd experiment a bit more with the step max slope angle, as it actually can have quite the impact even at seemingly odd angles, but fixing the behavior in one case might break it for a different case.

Alternatively you could try to add some "cheat" colliders to the areas that give you trouble (like a small cube at the top of the pyramid or a slope to the one step that seems to stop the player. This is actually how most games solve this.

**Comment by Phazorknight** [comment]
Hey @PeterD23 , @mrezai did some tweaks on the player controller. Maybe give https://github.com/Phazorknight/Cogito/commit/6dae7504bc3a007d56f86870345a9c36a26f6445 a go and see if it helps with some of your issues?

**Comment by Phazorknight** [comment]
Closed due to inactivity. Feel free to reopen if still an issue.

**Comment by hemebond** [comment]
It's possible to get stuck on the stairs in the laboratory just by walking at an angle along the wall. In fact I get stuff often on this wall.

In this screenshot I am just walking forward, no other keys pressed.

![Image](https://github.com/user-attachments/assets/827d1580-cd87-4286-9e25-ac9ace6d17ad)
