### ISSUE TITLE
When opening the inventory, the player is frozen while the world keeps moving.

### ISSUE THREAD

**Issue by Oldos4** [Phazorknight/Cogito#209]
**Cogito and Godot Engine Version:**
Cogito BETA 202401.13
Godot v4.2.2.stable.official [15073afe3]

**Description:**
When opening the inventory, the player is frozen while the world keeps moving.

**Reproduction steps:**
1. Stand on the moving platform
2. Open the inventory
3. Wait for the platform to move away
4. Close the inventory

**Expected behavior:**
I expected the character to keep moving along with the platform he's standing on

**Screenshots:**
https://youtu.be/BSXg5u8rF0E

**Comment by Phazorknight** [comment]
Hi Oldos, 

This is a legacy bug, please download the latest version of COGITO from GitHub here and this should no longer happen.

**Comment by Phazorknight** [comment]
Closing.
