### ISSUE TITLE
Another null error

### ISSUE THREAD

**Issue by theclaytondab** [Phazorknight/Cogito#21]
The error is "Invalid get index "player_interaction_component""
![Screenshot 2024-01-10 7 45 26 PM](https://github.com/Phazorknight/Cogito/assets/115123152/f423b34a-3bac-4d68-88fd-91e9d3ca1c6e)
![Screenshot 2024-01-10 7 43 08 PM](https://github.com/Phazorknight/Cogito/assets/115123152/843c33cb-e5ec-47dd-bd7a-2cd7b2894e27)
![Screenshot 2024-01-10 7 42 54 PM](https://github.com/Phazorknight/Cogito/assets/115123152/7131837d-b3c5-41b0-beef-97c7523dac59)

**Comment by Phazorknight** [comment]
Thanks for catching this!

This error happens when the player tries to use an item that is not in their inventory, but in a container like the chest.
I will add a conidition check to avoid this from happening in the next update, hopefully later today.

**Comment by Phazorknight** [comment]
Should now be fixed in **experimental/BETA 202401.8**

**Comment by theclaytondab** [comment]
Thanks
