### ISSUE TITLE
Flashlight not always turning on/off properly when used while walking/running.

### ISSUE THREAD

**Issue by Phazorknight** [Phazorknight/Cogito#213]
**Cogito and Godot Engine Version:**
Cogito beta 202405.16 / Godot 4.2.1 stable

**Description:**

**Reproduction steps:**
1. Start scene.
2. Pickup and equip flashlight.
3. Start walking/running.
4. While moving, click LMB to turn on/off flashlight.
5. Flashlight animation and sound gets triggered, but on/off state doesn't get updated each time as expected.

**Expected behavior:**
Flashlight on/off state should update everytime the sound/animation plays.

**Comment by KrysisDK** [comment]
I fixed this issue + added a few more features to the flashlight for immersion purposes on my fork.

Thank you for this git, it's truly an amazing time-saving project.

**Comment by Phazorknight** [comment]
@KrysisDK oh, would you mind putting in a pull request with your changes? Would love to take a look!

**Comment by KrysisDK** [comment]
@Phazorknight Done, thanks again

**Comment by Phazorknight** [comment]
Amazing, thank you so much.

Closing!
