### ISSUE TITLE
Inventory item tooltip remains visible when mousing off the inventory panel

### ISSUE THREAD

**Issue by BryceBarbara** [Phazorknight/Cogito#217]
**Cogito and Godot Engine Version:**
The Cogito pulled from master - v4.3.beta1.mono.official [a4f2ea91a]

**Description:**

**Reproduction steps:**
1. Put an inventory item in one of the edge inventory slots.
2. Mouse over the inventory item, see tooltip appear
3. Move the mouse off the inventory panel without mousing over any other inventory slots
4. See the tooltip remain visible

**Expected behavior:**
Tooltip disappears as soon as the mouse leaves the inventory panel

**Screenshots:**

https://github.com/Phazorknight/Cogito/assets/24460210/1ecd2afc-c986-4857-b71e-fafe761b6c46

**Comment by Phazorknight** [comment]
Thanks for flagging, was aware of this and finally got around to fixing it in https://github.com/Phazorknight/Cogito/commit/7561b22da96fbde44d4a6270aa4077f8f67807ca

Let me know if this still gives you trouble.

**Comment by Phazorknight** [comment]
Closing issue.
