### ISSUE TITLE
Game crashes when pressing Esc afther going to the laboratory from the lobby

### ISSUE THREAD

**Issue by prashannathapamagar** [Phazorknight/Cogito#218]
**Cogito and Godot Engine Version:**
4.2.2

**Description:**
After pressing the play button in godot engine 4.2.2 and spawning in the  lobby then i go to the laboratory through the hallway then i press Esc in the laboratory and the game crashes, and gives errors.
Interestingly  if i load the laboratory scene separately i can press Esc and the game does not crash on me.    
Can it be due to template not properly installing as it say several files are missing when i open the project even though i am using the most up to date template from your github page.

**Reproduction steps:**
After pressing the play button in godot engine 4.2.2 and spawning in the  lobby then i go to the laboratory through the hallway then i press Esc in the laboratory and the game crashes, and gives errors.
Invalid get index 'player_state_screenshot_file' (on base: 'Nil').

**Expected behavior:**
When i press Esc the menu should open.

https://github.com/Phazorknight/Cogito/assets/164744609/91648e85-3307-465e-bd48-d6d2c78e623a

**Comment by Phazorknight** [comment]
Hm, the error seems to be related with the created screenshot file… or lack of.
Could you try deleting any and all save files (scene states and player states) and see if that helps?

**Comment by prashannathapamagar** [comment]
Well it worked sorry for the inconvenience i caused. I had removed and installed the template multiple times but couldn't fix it . thank you !

**Comment by Phazorknight** [comment]
No worries, I'm glad it worked!
The save files stick around even if you re-install the template, so it can be a tricky issue to fix/find.
