### ISSUE TITLE
Readables not able to scroll with mouse - mousing over inventory spaces causes text to scroll

### ISSUE THREAD

**Issue by DaveA2021** [Phazorknight/Cogito#221]
**Cogito and Godot Engine Version:**
beta 202406.02
Godot 4.2.2

**Description:**
When interacting with readables that have scrolling enabled, the player is unable to scroll the text with the mouse wheel or by clicking the visible scroll bar.
mousing over squares inside the inventory GUI causes the text to scroll whether the readable is visible on the screen or not 

**Reproduction steps:**
1. Open Readable that has Scrolling enabled
2. attempt to scroll text
3. text does not scroll
4. open inventory and readable at the same time
5. mouse over inventory boxes
6. text begins to scroll

**Expected behavior:**
The expected behavior is to be able to move the scroll bar with the mouse wheel or by clicking on the visible bar.

**Screenshots:**

Follow Focus Script :-
![image_2024-07-09_222234293](https://github.com/Phazorknight/Cogito/assets/94810625/bb27c4c6-0521-4f5f-bd79-312b7a318cc3)

Readable Script:-
![image](https://github.com/Phazorknight/Cogito/assets/94810625/a9d5be7d-f7f1-4dc3-a52e-f09df111e4ff)

Inventory Slot Script:-

![image](https://github.com/Phazorknight/Cogito/assets/94810625/a183a9ac-9d42-4dd9-a796-499f1466d12b)

**Comment by DaveA2021** [comment]
Thanks for your response! I have not changed the set up as far as I know (unless I did something by accident) but here is the book in question:-

![image](https://github.com/Phazorknight/Cogito/assets/94810625/e50982d6-9c14-4034-aaf7-4da302f7c292)


![image](https://github.com/Phazorknight/Cogito/assets/94810625/4d8e7173-b342-4be3-88e6-845c2ef717d3)


I also noticed that if I add paragraphs to another readable I have, I also cannot scroll.

**Comment by Phazorknight** [comment]
Hm... would you mind sharing the node setup of your scene?

For anything UI related, node order inside the hierarchy matters, so I suspect that somehow another node might be "on top" of your readable, blocking the input.

As a quick test, you could try putting your readable object into one of the demo scenes as well and see if that changes the behavior.

**Comment by Phazorknight** [comment]
Don't feel silly! I've run into this problem more times than I can count.
Glad you were able to solve it!
