### ISSUE TITLE
Character can't move in demo and no explanation why

### ISSUE THREAD

**Issue by CloudyTabzy** [Phazorknight/Cogito#234]
**Cogito and Godot Engine Version:**
Cogito beta 202406.02/[pull request #223](https://github.com/Phazorknight/Cogito/pull/233) 
Godot 4.2.1 Stable

**Description:**
Request for ~idiot-proof~ beginner-friendly [documentation](https://cogito.readthedocs.io/en/latest/gettingstarted.html) of trying COGITO and its demo. I'm a _fairly_ new user of Godot and can understand the basics of its interface and been coding in GDScript for a while now. 

Unfortunately, following the documentation still left me puzzled for about 30 minutes until I figured everything out, your helpful [video](https://www.youtube.com/watch?v=SQbkcf1Ql4c) did help, but still doesn't show the step-by-steps.

ALSO, after loading the Lobby demo, the movement isn't working and the up & down mouselook is inverted. Looking up the [docs](https://cogito.readthedocs.io/en/latest/manual.html#player-controller), the movement controls are "self-explanatory", so I assumed it's already bound to the WASD key.

I understand this project is still under active development and the documents aren't always updated. So that's why I wish to update the docs since there might be beginners that could also get stuck getting through the demo. ~Or I might just be an idiot~

**Reproduction steps:**

1. Downloaded the latest zip file of COGITO, being [pull request #223](https://github.com/Phazorknight/Cogito/pull/233) 
2. Followed the [getting started documentation](https://cogito.readthedocs.io/en/latest/gettingstarted.html) and YT [COGITO Tutorial](https://www.youtube.com/watch?v=SQbkcf1Ql4c) to a T.
3. Tried the Lobby demo level and got stuck in place due to not knowing the movement controls and how to fix the inverted up&down mouselook.
4. Searching up the open and closed issues doesn't present the same issues I have, and the docs doesn't really explain much.

**Expected behavior:**
A "more" easy-to-follow guide to setting up COGITO and possibly improving the docs for a more streamline approach. Maybe with screenshots or video for more visualization.

**Screenshots:**
I would love to show the issue of me being stuck in place in video with keyboard logging/screencast, but my AMD Radeon ReLive crashed while loading the Demo level. I'll try with other recording software if really needed.

**Comment by CloudyTabzy** [comment]
Hold on, it might just be because my controller was plugged in, which overwrites the WASD keys on my keyboard.
Though I can't confirm this yet, my AMD Radeon Software keeps crashing whenever I play the game now.
![AMDCrashing](https://github.com/user-attachments/assets/82debc93-7b99-43a2-9c8f-d95a3707d9b0)

Gonna have to fix this if this is the case. Sorry in advance!

**Comment by Phazorknight** [comment]
Hey Cloudy, welcome to COGITO and sorry to hear it gave you some trouble getting it running. I'll look into adding more information in the documentation on what the default controls are.

Please let me know how it goes/if the behavior changes if you don't have your game pad plugged in.
Does it all work with the gamepad itself? What gamepad are you using?

Cogito itself is setup to support keyboard and mouse AND gamepad at the same time pretty much, certain things switch depending on which is currently active.
The input device detection assumes a generic gamepad, so I'm curious if some issues might be caused by specific ones.

Invert mouse Y is an in-game setting, so that'll be the first place to adjust this to your liking. This then gets saved in your games config, so it should "stick", but it might revert on build, since build games have their own config file in Godot.

**Comment by CloudyTabzy** [comment]
Yeah, I was really tired and frustrated getting through COGITO for the first time. I know it's not your fault nor the documentation, it's just that my first impression was kinda... disheartening, to say the least.

I know the potential of this template and I would love to work with it, but trying the project multiple times and encountering issues right off the bat is not very welcoming, especially with even my own AMD Radeon software keeps crashing the project and displaying these errors after recording it.
![COGITOErrors](https://github.com/user-attachments/assets/6e385a40-592e-4933-8afc-26e270e3be4b)


It's fixed now though, after deleting the project and redoing the setup again. Although...

**Comment by CloudyTabzy** [comment]
I found these errors keep happening once I loaded up the demo scene, and they keep displaying even after closing the game. Is there a step I missed?
![CogitoMoreErrors](https://github.com/user-attachments/assets/59430a49-052c-44f6-a86c-1fb04509a4e4)
![CogitoMoreErrors2](https://github.com/user-attachments/assets/ce8e7559-93d9-418a-9ec1-5fb24309b072)
![CogitoMoreErrors3](https://github.com/user-attachments/assets/e2d07409-160e-4d4b-8bec-9b0164722cf9)

Not exactly a welcoming sight for a first time user... Getting all those 62914 errors popping up for nearly 4 minutes, just to play a demo scene that doesn't register my inputs.

**Comment by CloudyTabzy** [comment]
> Please let me know how it goes/if the behavior changes if you don't have your game pad plugged in. Does it all work with the gamepad itself? What gamepad are you using?
> 

I'm using a PS3 controller that's been registered to the Xinput, sadly unplugging it doesn't seem to fix the issue.


> Cogito itself is setup to support keyboard and mouse AND gamepad at the same time pretty much, certain things switch depending on which is currently active. The input device detection assumes a generic gamepad, so I'm curious if some issues might be caused by specific ones.
> 

I assumed this too, played a lot of games where both the keyboard and controller are interchangeable, switching icons in-game whenever either of them are detected. I also wonder if it's because of my controller or not...?

> Invert mouse Y is an in-game setting, so that'll be the first place to adjust this to your liking. This then gets saved in your games config, so it should "stick", but it might revert on build, since build games have their own config file in Godot.

Yeah, I just noticed this in the main menu. I expected that I can change it in-game once I tried it, but seeing as I can't even open the pause menu with the 'ESC' key in-game due to the many errors presenting itself, I'd say this is my fault for associating this as an issue. Turns out there's bigger issues at hand.

**Comment by Phazorknight** [comment]
> demo scene that doesn't register my inputs.

Good news is we found the issue. Your project doesn't have the required input map actions defined. That's also why it looks like so many errors, as there will be several triggered each frame this way.

If you create your own project and then just copy COGITO into it, the godot project settings will be missing.

I recommend to instead use the whole COGITO project instead (loading a copy of it instead of creating a new Godot project), this way all your input maps (as well as the autoloads and plugins required) will be set up and it should run wihout any extra steps.

**Comment by CloudyTabzy** [comment]
Would you look at that, it works! My mistake, I guess I really am a beginner, huh? New to this while Github repository thing since I've always downloaded from the releases and pasting them into my own projects. Turns out it's the other way around, so sorry.
You might want to refer anyone to this issue if there's any would-be amateurs out there that made the same mistake as me in the future.

I'm more of a 3D designer/modeler and writer than a programmer, so I'll take this as a lesson learned from now on. Anyways, guess I'll close this issue now. And I'll be sure to share my game project or anything related in the discussion in the future, cheers!
