### ISSUE TITLE
Demo hint collision behavior is non-immersive

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#242]
**Cogito and Godot Engine Version:**
Cogito: beta 202407.01
Godot: 4.2.2

**Description:**
Cogito Demo Hints are static collision objects, which can collide and act as platforms for holdable objects, similar to furniture.

**Reproduction steps:**
1. Go to the starting point of the game
2. Hold a wastebin or planter pot
3. Move it into or on top of the Cogito Demo Hint

**Expected behavior:**
Cogito Demo Hints are non-colliding objects.

**Screenshots:**
![Cogito_Demo_Hint_Collision](https://github.com/user-attachments/assets/35575fd7-feae-4e0b-82c7-bcc37276e286)

**Suggestions:**
I was easily able to get around this by changing the cogito_demo_hint root type from StaticBody3D to Area3D, and then in cogito_player checking the "InteractionRaycast" RayCast3D child of Camera to "Collide with Areas".

The obvious concern is any new issues that arise from interaction raycasts detecting areas.

**Comment by Phazorknight** [comment]
Hey, so there's an easier solution to this:
Just disable the first collision layer on the Demo Hints.

![image](https://github.com/user-attachments/assets/f6a6da54-f668-4a15-835a-f4300909a6b5)

This way, the Interaction Raycast still picks them up as expected, but objects like the planter or the cups don't collide with them.

Will consider updating this in the next commit as well.

**Comment by OvercastInteractive** [comment]
Even better, great! 😁

**Comment by Phazorknight** [comment]
I've updated this in https://github.com/Phazorknight/Cogito/commit/ed83c1327773f7d13c6a804b4b0bfe124350f719, considering this issue resolved.
