### ISSUE TITLE
swimming [feature request]

### ISSUE THREAD

**Issue by ZeroHanekoma** [Phazorknight/Cogito#245]
Sorry I don't really use GitHub too much except for comments.  This is something I hacked in somewhat.  Still figuring out how to make it work with the interactables but I got the player swimming lol.
Not too terribly hard.  Check if the player is in an Area3d with a certain group, if so do swimming behaviors.

**Comment by Phazorknight** [comment]
Hello and welcome!

That's awesome, would love to see it! Would you mind putting in a pull request with your swimming feature? That way we can take a look at the code and possibly integrate it in the main branch.

**Comment by ZeroHanekoma** [comment]
I had to skeleton it together from 2 different plugins and a tutorial I had recently followed, but I can definitely upload what I've done to get it working.  It's still a little... funny but it works more or less.

**Comment by Phazorknight** [comment]
Closing this issue as discussion has now moved to #246
