### ISSUE TITLE
Crash on reloading wielded item after scene transition

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#25]
Attempting to reload a wielded item that was held when going through a scene transition causes crash with the error "Attempt to call function 'get_parent' in base 'previously freed' on a null instance." If you put the wielded item away and pull it out again this does not occur.

**Comment by Phazorknight** [comment]
Thanks for flagging this. I'm aware of this, there's currently multiple bugs associated with wieldables and saving/transitioning scenes. Hoping to get to these soon.

**Comment by Phazorknight** [comment]
This should be fixed in **BETA 202401.11**, coming later today.
There's still some weirdness with how wieldables behave after loading a save or scene transition, but this error should no longer occur.
