### ISSUE TITLE
Shooting projectiles on enemy makes COGITO crash.

### ISSUE THREAD

**Issue by MathieuBK** [Phazorknight/Cogito#252]
**Cogito Version:**  
Cogito Beta 202407.01

**Godot Engine Version:**  
Godot v4.2.2.stable

---

### Issue Description:
When shooting projectiles at enemies, the game crashes with the error:

```
Invalid get index 'cogito_properties' on base 'CharacterBody3D (CogitoEnemy)'
```

This error originates from the `cogito_projectile.gd` script.

### Steps to Reproduce:
1. Start a new game.
2. Navigate to the Laboratory.
3. Pick up the "Pistol Foam" in the "Shooting Range" room on the right.
4. Proceed to the "Movement" room.
5. Shoot the enemy on the platform.

### Expected Behavior:
The enemy should take damage and be destroyed, similar to the behavior observed when using the Blaster.

### Screenshots:
![Error Screenshot](https://github.com/user-attachments/assets/930580d5-7050-4771-9109-8dc8ad44dffe)

### Quick Fix:
The error seems to occurs because the `CogitoEnemy` object does not have a `cogito_properties` property, but the projectile script assumes its existence. To resolve this issue, the `_on_body_entered()` function in the `cogito_projectile.gd` script could be modified to check whether the collider actually has the `cogito_properties` property before attempting to access it.

Here's the updated code snippet:

```gdscript
func _on_body_entered(collider: Node):
	# Check if the collider has the `cogito_properties` property
	if collider.has_signal("damage_received"):
		if !cogito_properties:
			print("Projectile: No properties defined on the projectile.")
			deal_damage(collider)
			return

		if collider.has_method("get_cogito_properties"):
			var collider_properties = collider.get_cogito_properties()
			if collider_properties:
				# Handle different cases based on material properties
				if cogito_properties.material_properties == CogitoProperties.MaterialProperties.SOFT and collider_properties.material_properties == CogitoProperties.MaterialProperties.SOFT:
					print("Projectile: Soft object hit, dealing damage.")
					deal_damage(collider)
				# Add additional cases as needed...
			else:
				print("Projectile: Collider does not have cogito_properties, damaging as usual.")
				deal_damage(collider)
		else:
			print("Projectile: Collider does not have get_cogito_properties method, damaging as usual.")
			deal_damage(collider)
	else:
		if destroy_on_impact:
			die()
```

This change ensures that the projectile only tries to interact with `cogito_properties` if the collider actually has that property, preventing the game from crashing.

**Comment by Phazorknight** [comment]
Hey MathieuBK, thanks for this flag.

The current enemy is very new and still has quite a few issues.
You've identified the issue with the properties and I appreciate the solution, will try to implement it into main in the coming days.

I'll probably still also add proper property support to the enemy itself so you can have enemies that can be affected by them as well.

**Comment by Phazorknight** [comment]
Hey @MathieuBK , I've pushed a small update that adds cogito property support to the enemy. It's still WIP and I plan on refining this overall but should hopefully fix this issue.

**Comment by Phazorknight** [comment]
Closing, assuming resolved.
