### ISSUE TITLE
Gamepad, Player Inventory: Dropped Inventory Item Count Inaccuracy

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#259]
****Cogito** and Godot Engine Version:**
Godot: 4.2.2.stable
Cogito: beta 202408.02

**Description:**
Using a gamepad, when dropping _any stackable_ inventory item from a slot containing multiple items (x4 laser ammo) always drops 1 less than the amount from inventory (x4 laser ammo only drops 3).

**Reproduction steps:**
1. Use a gamepad
2. Accumulate multiple laser ammo from the vending machine
3. Drop them all from inventory

**Expected behavior:**
The full amount of laser ammo you had in inventory is dropped.

**Screenshots:**
![Cogito_Inventory_LaserAmmo_01](https://github.com/user-attachments/assets/1b52a4bf-0220-48fb-9217-4260f0d2ff8f)
![Cogito_Inventory_LaserAmmo_02](https://github.com/user-attachments/assets/86caadd1-4408-4bc8-9ef9-e9ff8cae940c)

**Comment by OvercastInteractive** [comment]
Dropping items _individually_ using the mouse drops the correct amount, so it's just a matter of ensuring gamepads behave just like mouse clicks.

**Comment by OvercastInteractive** [comment]
The mouse behavior works great now!

Here's a closer look at the gamepad issues:

When dropping 4 laser ammo in a row the slot quantity (shown below) changes in this order:
(inventory shows x4) -> drop -> (inventory shows x3) -> drop -> (inventory shows x1, skipping x2)
However the item quantity shows something different.
When dropping from x4 to x3 the slot quantity shows 2
When dropping from x3 to x1 the slot quantity shows 0
When dropping from x1 to null the slot quantity shows -2

![Cogito_Inventory_Drop_Quantity_When_Dropping_04](https://github.com/user-attachments/assets/2538e6e7-2a18-454e-bc70-5539ac1c5f5d)

If you pick up and have only 1 laser ammo in an inventory slot and drop it, it states the slot quantity is now -1
If you pick up 2 laser ammo in an inventory slot, after dropping the first one the slot quantity is now 0, and after dropping the second the slot quantity becomes -2.

![Cogito_Inventory_Drop_Quantity_When_Dropping_05](https://github.com/user-attachments/assets/3767625b-b5ac-4e73-84b5-122efb972e6f)

**Comment by Phazorknight** [comment]
Thanks for this, helped me narrow down the culprit, and this should now be fixed in https://github.com/Phazorknight/Cogito/commit/12508b72eb91a11c6a0463888ac100ad695280a5 

The mouse uses two separate stacks, or more precisely, two separate slots: once the slot in the inventory, then the _grabbed_ slot that sticks to your mouse cursor when moving or dropping items. Using the same methods for game pad accidentally reduced the total number of items (as instead of two stacks, one stack was assumed that got reduced twice). I've separated out a method specifically for game pad item dropping, which should fix this.

**Comment by OvercastInteractive** [comment]
Thanks for the info, I had suspected something like that.
Tested and can confirm it's working properly on my end as well.
Thanks!

**Comment by Phazorknight** [comment]
Good to hear. Closing!
