### ISSUE TITLE
Input Device, Player Inventory: Stackable Item Drop Behavior Inconsistency

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#260]
**Cogito and Godot Engine Version:**
Godot: 4.2.2 stable
Cogito: beta 202408.02

**Description:**
When dropping stackable items using a gamepad, each item in the stack is dropped individually (e.g. if working correctly, x4 laser ammo in inventory drops 4 separate laser ammo assets, each containing 1 laser ammo)
Yet when dropping stackable items using a mouse all items in the stack are dropped collectively (e.g. x4 laser ammo in inventory drops a single laser ammo asset containing 4 laser ammo)

**Reproduction steps:**
1. Spawn multiple laser ammo from the vending machine
2. Using a gamepad, drop them all
3. Get the same amount of laser ammo from the vending machine again
4. Using a mouse, drop them all

**Expected behavior:**
Dropping behavior is as consistent as possible across all input methods

**Screenshots:**
Using mouse: (there are 4 laser ammo in the dropped item)
![Cogito_Inventory_LaserAmmo_03](https://github.com/user-attachments/assets/b7f175b1-19fb-48bd-a395-0243e7ea732a)
Using gamepad: (there's another issue open about the number of items dropped using gamepad, that's why there's only 3)
![Cogito_Inventory_LaserAmmo_04](https://github.com/user-attachments/assets/0ad75760-f589-4874-aa76-171903c64820)

**Suggestions:**
Dropping stackable items _individually_ makes more sense to me because it allows for more fine-grained controlled over your inventory and use of items that need to be placed in the world. For example, if you need to collect puzzle pieces and have a stackable inventory item that can hold 5 puzzle pieces, you should want to be able to drop them individually. The same logic applies for other types of items like dice or weights or Cogito Properties items that don't make sense as single dropped item (secretly) containing multiples of that item.

I understand you can use the 'Use' behavior to do some of this, but considering more dynamic or modular Cogito Properties items, if you have a stackable item that can hold x5 conductive rods and you have various places in the world where you want to drop and place them to form a circuit you would need to be able to drop them individually. Maybe there are other types of conductive items you can use besides a rod in this example, but you want to save them and use a single rod from inventory instead because you're managing your resources carefully, you would want to be able to do that.

**Comment by Phazorknight** [comment]
Fully agree with your suggestion.
The _dropping a whole stack as one item_ is a leftover from the legacy inventory system. Technically that system offers both (while the inventory is opening, depending if you press left or right mouse button while you move an item over the drop-area). But getting rid of the _stack drop_ would make the behavior more consistent.

Will look into this, shouldn't be too hard to get rid of.

**Comment by Phazorknight** [comment]
@OvercastInteractive this should now be implemented in https://github.com/Phazorknight/Cogito/commit/afdb5d5a8b33de643f0745cf30d6282d312abb8c

**Comment by OvercastInteractive** [comment]
The behavior now feels consistent between input devices, thanks!

**Comment by Phazorknight** [comment]
Sweet, closing.
