### ISSUE TITLE
Save System: Picked up objects, door and window states all reset on scene load

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#263]
**Cogito and Godot Engine Version:**
Godot: 4.2.2
Cogito: beta 202409.02

**Description:**
Picking up objects (flashlight, ripped pages) can be picked up again and again, if you follow the reproduction steps below.

**Reproduction steps:**
### Critical
1. Start a new game
2. Exit the Lobby to the Laboratory without doing anything else
3. Return to the Lobby
4. Pick up any of the picks around
5. Save from menu
6. Load from menu (notice the objects return)
7. Leave again to the Laboratory and repeat

**Expected behavior:**
Objects don't return after being picked up and saved.

**Screenshots:**
![Cogito_Object_Pick_Up_Save_Issue_02](https://github.com/user-attachments/assets/a57af5ec-f0f2-4d65-a832-591a41b2f31b)

**Comment by OvercastInteractive** [comment]
I just tested this a bit further because I noticed the doors and windows, including the locked security room door, also reset to their default state on reload when following the same reproduction steps. I was about to write another issue for them but these two issues are related, it's not just for pick ups and may have something to do with the temp save states instead.

**Comment by Phazorknight** [comment]
Yeah, this clearly sounds like an issue with how the save files themselves are managed.

I have an idea to what's causing this, but will have to look into this properly when I have more time later this week.
I don't think the temp save files get deleted before a save file is loaded, and then I suspect that the existing save files aren't detected properly which would cause scenes to load their "vanilla" state (eg. all items present).

**Comment by Phazorknight** [comment]
Ok, I just pushed https://github.com/Phazorknight/Cogito/commit/5182d7ad93e02ed3ff3b4beafbb2bc089e3082f4 which should fix this issue.

**Comment by OvercastInteractive** [comment]
It looks to be fixed! 👍

**Comment by Phazorknight** [comment]
Great! Closing.
