### ISSUE TITLE
Firing toy gun returns error 'Invalid get index 'wieldable_damage' (on base: 'Nil').'

### ISSUE THREAD

**Issue by Ophiolith** [Phazorknight/Cogito#27]
I haven't really dived into the code of the demo, and my GDScript knowledge is not great, but currently firing the demo toy gun wieldable consistently errors out with the message described above. From what I'm able to see, when wieldable_pistol.gd tries to set its value by calling wieldable_damage on line 35, for some reason it can't call the correct value from the passed reference.

I've not made any changes or tweaks to the demo, I'm just running it unmodified on 4.2.1

I imagine this is just a case of fixing an errant reference, but I'm just getting my head around the code so not sure where to start. Eitherway, congrats on the otherwise stunning template.

**Comment by Phazorknight** [comment]
Thanks for flagging this!
Was able to reproduce. Will be fixed in the next commit **BETA 202401.11** , coming later today.
