### ISSUE TITLE
Droppable Items, Gamepad: Pressing 'Drop' for undroppable items results in errors

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#273]
**Cogito and Godot Engine Version:**
Godot version: 4.2.2
Cogito version: beta 202409.03

**Description:**
Using a gamepad, press 'Drop' on an undroppable in inventory, and while it's still selected press 'Use' to trigger an error.

**Reproduction steps:**
1. Make sure to use a gamepad
2. Add an is_droppable = false item into the Cogito Lobby
3. Add it to inventory
4. Press the 'Drop' input (the interaction prompt still shows it's possible)
5. Doing this puts you into a move item-like mode
6. Press the 'Use' input to trigger the error

**Expected behavior:**
When the player presses drop input, nothing happens. And they're able to move the undroppable item around in the inventory like any other item, which is important because player's need to be able to rearrange items as they see fit.

**Screenshots:**
![Cogito_Inventory_Set_Region_For_Undroppable_Issue_01](https://github.com/user-attachments/assets/00458d1e-5dfe-458e-9c00-e0f635712881)

**Comment by OvercastInteractive** [comment]
Another issue: 

Reproduction steps:
1. Do steps 1-4 in the top post
2. Select a different inventory slot (while the undroppable is in a move item-like behavior)
3. Press 'Move' input
4. The item appears to duplicate

![Cogito_Inventory_Set_Region_For_Undroppable_Issue_02](https://github.com/user-attachments/assets/2c769bd8-5ec5-4553-8235-bf544a8000a2)


These issues only appear after selecting 'Drop' on an undroppable item. Perhaps if we simply ignore the 'Drop' input when selecting an undroppable item they will both be resolved.

**Comment by Phazorknight** [comment]
Thanks for flagging this behavior.
Please see https://github.com/Phazorknight/Cogito/commit/313cf30020697921d3df1a9af6b1908a35f01429 for a fix, let me know how that works for you.

I've also updated the inventory hud to hide the "drop" prompt if an item is not droppable. If the player still presses the "drop" button, an error sound will be played.

**Comment by OvercastInteractive** [comment]
The 313cf30 fixes the issues and falls in line with expected behavior. Hiding the button along with playing an error sound emphasizes the unavailability of the action, which I appreciate as well.

**Comment by Phazorknight** [comment]
Great, closing issue.
