### ISSUE TITLE
Items can be duped using drop function on gamepad.

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#28]
If you use a gamepad on the inventory screen with an equipped wieldable, when you press drop, it will play the denial noise then create a duped version of said wieldable to be moved. You can place it in an open slot and make a new one. 
Also, if you close the inventory window while moving an item, the item appears to disappear until you click another slot.

**Comment by Phazorknight** [comment]
Thanks for these flags!

Both should be fixed in BETA 202401.12
