### ISSUE TITLE
ETA for 4.3 update?

### ISSUE THREAD

**Issue by brickyt** [Phazorknight/Cogito#280]
Hello @Phazorknight I have been playing around with Cogito (amazing work! ty so much for sharing your talents with the community!) and want to implement various parts (inventory, attributes, interaction) into my 4.3 FPS prototype (using Chaff's FPS Template https://chafmere.itch.io/godot-4-fps-pro) and wanted to know when you expect to have a 4.3 update to Cogito?

Also, if there are any best practices/pitfalls you are aware of when plugging inventory, attributes, interactions into other projects I'd appreciate it! Cheers!

**Comment by Phazorknight** [comment]
Hey brickyt!
 
**4.3 update when:** There's currently no specific timeline as to when Cogito will be updated to 4.3 (but there also shouldn't be any major compatibility problems overall. I'd mainly expect some graphical issues). You can also see the discussion here: https://github.com/Phazorknight/Cogito/discussions/247 

**Chaff's FPS Pro** : I love Chaff's tutorials and weapon system. Without having looked into this further, I think Chaff's system is an "abstract" shooter inventory (Player has all the weapons and ammo in the weapons manager). So the main hurdle in getting FPS Pro to work with Cogito would be to reconcile Cogito's inventory and wieldable management with the FPS Pro weapon resources. 
Assuming you'd stick with Cogito's inventory, you'd have to change the FPS Pro weapon resource: Add a reference to a  cogito wieldable item resource and update the FPS Pro weapon's functions to use it for stuff like ammo checks etc.
You probably also have to update the PlayerInteractionComponents management of Wieldables a bit (checking if an FPS Pro weapon is held and so on).

**Comment by Phazorknight** [comment]
Closing this. For 4.3 update inquiries, refer to https://github.com/Phazorknight/Cogito/discussions/247
