### ISSUE TITLE
Errors on install 

### ISSUE THREAD

**Issue by TheBricktop** [Phazorknight/Cogito#29]
Hello, 
ive downloaded the project from github and while testing the project out of the box I got a bit of errors here and there :
- While just "running" the project starting from the menu there is no way to load the first demo scene using the integrated loader 
the error says : "E 0:00:22:0597   load: Cannot open file 'res://COGITO/DemoScenes/COGITO_Demo_01.tscn'."
and
"E 0:00:22:0598   _load: Failed loading resource: res://COGITO/DemoScenes/COGITO_Demo_01.tscn. Make sure resources have been imported by opening the project in the editor at least once."
- Another error appeared when playing out of the demo 1 scene when tried to use the toy gun:
"Invalid get index 'wieldable_damage' (on base: 'Nil')." on line 35 in Wieldable_Pistol

Is there any step that Ive forgot in the process of installing the framework?

**Comment by Phazorknight** [comment]
Hi, thanks for checking out the project.

Can you confirm which version you're running?
The first two errors were some incorrectly set references that should've been fixed a few commits ago, so maybe try redownloading the latest /main/ branch commit.

**Comment by Phazorknight** [comment]
As I haven't heard anything for a while, I'm gonna close this issue.
