### ISSUE TITLE
Gamepad, Sittable: Unable to look around (and exit seat) while seated

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#303]
**Cogito and Godot Engine Version:**
Godot version: 4.2.2
Cogito version: beta 202409.04

**Description:**
Upon interacting with a sittable, lose the ability to look around (and therefore exit the seat in most cases) using gamepad.

**Reproduction steps:**
1. Use a gamepad
2. Click on a sittable

**Expected behavior:**
Look input continues to work upon being seated

**Comment by OvercastInteractive** [comment]
I saw the issue was noted in `cogito_player` and attempted a more top-down fix by converting joypad motion into mouse motion at the start of `_input()` and overwriting the event so it would be picked up as though it was a mouse motion input event but the results weren't good enough. I thought if we could simulate all look behavior as mouse input then we could simplify all of the following look rotation logic, but apparently joypad motion is best left to be processed in `_physics_process()` over `_input()` 😫

**Comment by niefia** [comment]
Had the exact same thought process on this issue, didn't have a controller to try it with but figured it must be in the `_physics_process() `for joystick specific reasons so couldn't do the easy option of just mapping it to mouse input first.

I've put out a quick update at #304  that just allows the controller code to run without being look restricted by the Sittables as that'd be better than the current total lack of implementation. 

Properly implementing it with the look restrictions would probably require a rework of it and take some time though.

**Comment by OvercastInteractive** [comment]
Thanks for the quick update, will make it much easier to test.

**Comment by OvercastInteractive** [comment]
This now works exactly as expected. Thanks to all involved!
