### ISSUE TITLE
In Windowed mode returning to full screen on main menu

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#319]
**Cogito and Godot Engine Version:**
Godot v4.2.1 b09f793f5
COGITO - current commit - c406d828c4e87b902dc020b2a58ebbb5ecf4ffe5

**Description:**
The game is not respecting my change to windowed mode after I apply it.

**Reproduction steps:**
Run the game from the main menu
Go to options, graphics tab, set window mode to windowed, hit apply changes.
Back out to main menu
Select a new game
Screen will briefly flash full screen, then return to windowed.
Open pause menu.
Click back to main menu.
The window returns to full screen

**Expected behavior:**
Once I set windowed and hit apply I expect the main menu to respect this setting when I return to it.

**Comment by Phazorknight** [comment]
I have the same issue. I don't think it's strictly related to the main menu itself.
For me it occurs that when I set the window mode, the settings stay saved for one re-start, then reset.

1. Run game (settings are reset/set to default, fullscreen mode)
2. Open options and change settings (windowed mode)
3. Close and run again.
4. Stored settings are loaded (windowed mode)
5. Close and run again
6. All settings are reset / back to default.

I assume it's an issue with how the config is saved/loaded, but haven't had a chance to look into it yet.

**Comment by Phazorknight** [comment]
I did some investigating and I think i've pinpointed the issue:

1. On loading the config file, the audio volume sliders are loaded
2. As these values are loaded, the `value_change` signals are emitted, which in turn called the `apply_changes_pressed`
3. This saves/overwrites the config file with the current values.
4. As the volume slider values are loaded _before_ the graphics settings, the default values for those are saved at this moment.

I've thus moved the loading of the volume sliders to the bottom, which seems to have helped.
Will put this into a future commit.

![image](https://github.com/user-attachments/assets/69fc64dc-1a51-4bc4-a9df-1c7362944afb)

**Comment by OvercastInteractive** [comment]
There is another issue with the options menu, apart from not saving settings, and that is when you change settings and don't hit apply the button and slider states don't revert to the actual settings when reopening the options menu.

Test:
Toggle the "Invert Y" checkbox to on, **don't** apply changes and resume playing.
Return to the options menu to find the "Invert Y" checkbox is still on, even though the actual behavior/setting is off.

If exiting the menu without applying changes, the menu buttons should be reverted to reflect their actual values.

**Comment by Phazorknight** [comment]
Ok, I just pushed some tweaks in https://github.com/Phazorknight/Cogito/commit/bfb1530ff2d496a18921ff2b9fb0be31dfb30f6c

The `Restore defaults` button is there but currently not functional or hooked up to anything.
This is a bit tricky to test, so please give it a go and report any Issues you encounter.

**Comment by ac-arcana** [comment]
I haven't encountered any issues with this. My original issues is resolved. I'm happy to close the issue.
@Phazorknight did you want this open for your notes for later, or is that is that un needed now?

**Comment by Phazorknight** [comment]
Yeah I'm gonna close this for now. Thanks!
