### ISSUE TITLE
Wrong paths for some image files

### ISSUE THREAD

**Issue by Yora0** [Phazorknight/Cogito#321]
### I'm just seeing that this very issue is already covered in a pull request, making this bug report obsolete.

**Cogito and Godot Engine Version:**
Godot 4.3

**Description:**
When opening the demo project, the Output window displays the following errors:

*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_InteractionComponent.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoProperties.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoCurrency.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_InteractionComponent.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoProperties.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoCurrency.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_InteractionComponent.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoProperties.svg (expected type: )
*Resource file not found: res://COGITO/Assets/Graphics/Editor/Icon_CogitoCurrency.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )
*Resource file not found: res://addons/cogito/Graphics/Editor/Icon_CogitoObject.svg (expected type: )

The directory /COGITO/Assets/Graphics/Editor does not exist.
The directory /addons/cogito/Graphics/Editor does not exist.

The missing files are in /addons/cogito/Assets/Graphics/Editor.

Looks like the directory has been moved, but references pointing to them have not been updated.

**Comment by Phazorknight** [comment]
Hey, thanks for flagging this.
Yeah, these are some old references that will be fixed once the Godot 4.3 update of Cogito goes into main. 
They shouldn't affect running the project though.

I'm gonna close this issue, but if there's anything breaking, please re-open or create a new one. Thanks!
