### ISSUE TITLE
Input Bindings error when joypad motion is detected

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#324]
**Cogito and Godot Engine Version:**
Cogito: beta 202410.02
Godot: 4.3

**Description:**
Get an "InputEventJoypadMotion" related error in `_unhandled_input()` in `kbm_bind_button.gd` when a gamepad is detected and selecting any input icon/button in the Input Bindings tab using the mouse

**Reproduction steps:**
Have a gamepad plugged in while playing and attempt to reassign an input binding using the mouse

**Screenshots:**
![Cogito_InputBindings_Pressed_Input_Error_01](https://github.com/user-attachments/assets/9d08d862-9019-42f9-8e14-c0584ba1f4f9)

**Comment by Phazorknight** [comment]
Thanks for flagging this!
I've just pushed a quick fix for this in https://github.com/Phazorknight/Cogito/commit/e332829253333b98d04471c1a7505213eab13dfb

This just exits the function if joypad motion is detected to avoid this error, the input binding is still buggy. 😓

**Comment by Phazorknight** [comment]
Closing this as initial issues has been resolved.
