### ISSUE TITLE
Add head/camera tilt as a menu option

### ISSUE THREAD

**Issue by kachek47** [Phazorknight/Cogito#326]
Hi there!
Thank you for the great framework, I'm really enjoying it so far. However, the way the camera will tilt slightly to the right or left when jumping or landing on the edge of something is making me a bit motion sick. I've gone through every head, neck, eyes, camera, tilt, bobbing, rotation etc. tag in the player scene I can find, and I still can't turn it off. Is it possible to add this as an @export option in the godot engine, similar to all the other camera movement options please?

**Comment by Phazorknight** [comment]
Hey, thanks for your kind words. And so sorry about the motion sickness!

I suspect this might be from the jump camera animation, as that one tilts the camera slightly.
Could you try the following?

In the `cogito_player` scene, find the _AnimationPlayer_ node and look at the `jump` animation. There's a camera rotation track that has one keyframe that slightly rotates the camera:
![image](https://github.com/user-attachments/assets/8db9530f-7b97-431b-b20f-78bb82164b37)

Select it, and then in the inspectior, change the Z value to 0.
![image](https://github.com/user-attachments/assets/f8d5fc2c-31fb-4d46-ad1a-cee11657420f)

Make sure to save it and then give it a test.

**Comment by kachek47** [comment]
Just got the head tilt turned off! Thanks so much for the fast reply and the detailed instructions, I really appreciate it :) And thanks again for making cogito.

**Comment by Phazorknight** [comment]
Awesome, glad to hear it helped!
I will consider removing the tilt going forward as you might not be the only person that this causes some motion sickness.
Should be able to find a way to add some bobbing through code that can be customzied easier.

**Comment by Phazorknight** [comment]
Head tilt animation was removed in the latest Cogito version, so I'm closing this issue.
