### ISSUE TITLE
Placing a stackable inventory item on a Switch empties the item's slot, instead of only reducing it by one

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#334]
**Cogito and Godot Engine Version:**
Godot 4.3
Cogito beta 202411.01

**Description:**
Switches that require inventory items to be placed empties the inventory slot instead of removing a single item from it.

**Reproduction steps:**
Pick up multiple batteries before placing a battery on the switch and notice the battery inventory slot is emptied.

**Expected behavior:**
Only one item is removed when placing an inventory item on a switch.

**Comment by Phazorknight** [comment]
Hey, thanks for flagging.
I feel like I've encountered this a while ago but fixed it. Could you retry this with the latest commits from main ( beta 202411.02 ) ? I've just tried this in the Laboratory scene, and it only removed 1 battery from the stack for me.

**Comment by OvercastInteractive** [comment]
My bad I must have still been on the _plugin_rework_ branch 🙏. Everything works great!
