### ISSUE TITLE
Attribute values not displaying the correct value upon change (fix included)

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#336]
**Cogito and Godot Engine Version:**
Godot 4.3
Cogito beta 202411.01

**Description:**
Adding values greater than 1 to an attribute has the potential to display a value greater than the max in the attribute UI.
I assume this would also display negative values if subtracting less than 0, but that's untested.

**Reproduction steps:**
Change the value of a consumable to exceed the max value and then consume it.

**Expected behavior:**
Attribute values are clamped between 0 and max.

**Screenshots:**
Changed the health potion to grant 75 health:
![Cogito_Attribute_Value_Beyond_Max_02](https://github.com/user-attachments/assets/90b6e622-a4a9-467b-8a8c-c8da361cdd69)

Clamping the value after evaluating the value change works:
![Cogito_Attribute_Value_Clamp_01](https://github.com/user-attachments/assets/be2dee5b-fb03-4dca-9202-746a7a95ee24)

**Comment by Phazorknight** [comment]
oh thanks for catching this!

This should now be fixed in https://github.com/Phazorknight/Cogito/commit/215cee5ab4dd4a5333adf5acd5e2c34b526a2d2b

**Comment by frendship-loost** [comment]
I noticed a similar problem with the light indication meter (or stealth bar?) where it would only update on movement.
E.G. if you entered a dark room, and turned on the lights without moving, Cogito will still think you are in darkness.

(I implemented a day/night cycle, so here I am standing in daytime with a very low light indication after not moving to update it)
![image](https://github.com/user-attachments/assets/a5d7587e-b372-4e01-80a3-20287c53b445)

**Comment by Phazorknight** [comment]
> I noticed a similar problem with the light indication meter (or stealth bar?) where it would only update on movement.

@frendship-loost 
This is intentional. The light meter detection can be performance-heavy, so this is one of the safeguards to avoid it updating every frame.

That being said, I just pushed an update to add an interval to force update it. So you can set it to update once every second or any other value.

**Comment by frendship-loost** [comment]
I didn't realize it was the intentional design of the feature. Thank you for explaining, and thanks once more for the fix!

**Comment by Phazorknight** [comment]
Closing this as original issue should be resolved now. Please reopen if not.
