### ISSUE TITLE
Ladders - Strafing/Sidestep Movement Bug

### ISSUE THREAD

**Issue by frendship-loost** [Phazorknight/Cogito#337]
**Cogito and Godot Engine Version:**
Latest main .zip Cogito download, Godot 4.3 stable.

**Description:**
Instantiate the ladder.tscn that is provided with Cogito into a test scene, climb the ladder and then sidestep or airstrafe (A, D movement keys) while on the ladder. The sideways movement allows you to walk through the collision.

**Expected behavior:**
The ladder collision should never be ignored. Somehow, ignore or disable airstrafe or sidestep movement while on ladders? I don't have the experience to say if this is a bug specifically with the ladder script, or the general movement system.

**Comment by Phazorknight** [comment]
Hey, just deployed a quick fix here: 
https://github.com/Phazorknight/Cogito/commit/8524047cc07d13dcde3d54e6e1ce1713c90795bd

So when on ladder, it used to be that only the specific collision is disabled. I think technically you could also just remove the reference to it in the inspector, and it should also work, but for now I just commented out the line of code that disables the collision mode.

**Comment by frendship-loost** [comment]
Thanks for the quick reply! I'll mark this closed/fixed.
