### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by wangluodaxia** [Phazorknight/Cogito#343]
![image](https://github.com/user-attachments/assets/9d21c4da-102d-4d11-952f-89183752872b)

i think here should be   inventory_item.name == other_slot_data.inventory_item.name ,  right?

**Comment by Phazorknight** [comment]
Are you encountering any issues or unexpected behaviour?

AFAIK, there's no bug here. This line works as it's comparing the resources these two references refer to.

**Comment by wangluodaxia** [comment]
ok
