### ISSUE TITLE
Stamina can raise when running.

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#35]
Hello ! 

Thank you for your work on Cogito, I am loving it <3.

I played a bit around with this wonderful groundwork and I guess I found a bug.

1) Install cogito.
2) Run the COGITO_01_Demo.tscn
3) Run around to drain your stamina. 
3.1) Stand still to wait for your stamina to increase. 
3.2) When the stamina starts to increse, start running again.
3.3) Watch stamina raising while running.
3.4) Stamina starts draining again after it reaches its "full state"

Maybe see the video attached:

https://github.com/Phazorknight/Cogito/assets/87974401/0cad7c3f-0738-400f-88f3-63be2f510513

**Comment by Phazorknight** [comment]
Hm, I remember this bug but I thought I fixed it.
Could you confirm with version of COGITO you are running?

**Comment by ksjfhor** [comment]
Hi, this _was_ on Version 202401.13 (from the assetlib) but on version BETA 202402.00 from github, it behaves as it should :)
Thank you !
