### ISSUE TITLE
Player Can Cause Foam Pistol to Drain Ammo as if Flashlight Battery

### ISSUE THREAD

**Issue by e-sarkis** [Phazorknight/Cogito#36]
![image](https://github.com/Phazorknight/Cogito/assets/19242610/a15bf3f1-c747-43bb-8557-51fe031caa83)
By activating the flashlight and switching to the pistol in quick succession, the foam bullets can be seen draining into-nonexistence as if battery power.

Please note the log message "Foam Pistol is out of battery."

**Comment by Phazorknight** [comment]
Oh, thanks for flagging this!

Have a rough idea how this can happen, will look into it.

**Comment by Phazorknight** [comment]
This is now fixed in BETA 202402.01:

The Flashlight will now always turn off when unequipping, thus preventing it from draining itself or other wieldables when not in use.
