### ISSUE TITLE
Lean

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#37]
How about lean controls with default Q and E, as in many FPS shooters?

**Comment by fantasticaneer** [comment]
This would be excellent!

**Comment by ac-arcana** [comment]
I note that there is already a use for the E key, which is to carry an item. This could perhaps be a F hold instead of a separate input.

**Comment by Phazorknight** [comment]
As this is a game design-specific that is relatively niche, I currently don't have any plans in implementing this.
Happy to review a PR if someone else wants to add this.

**Comment by ac-arcana** [comment]
I'll work on it (though probably not today)

**Comment by ac-arcana** [comment]
I still plan to add this as a feature eventually, but I'm pretty distracted with my multiplayer add-on. This also is just not needed to reach 1.0. As such I am going to close this issue, and I'll get to this feature when I get to it.
