### ISSUE TITLE
Mouse sensitivity option

### ISSUE THREAD

**Issue by fantasticaneer** [Phazorknight/Cogito#38]
Would appreciate a mouse sensitivity slider by default.

**Comment by ac-arcana** [comment]
There are also joystick sensitivity and joystick deadzone values for controller, that could be included in options as well

**Comment by Phazorknight** [comment]
Fully agree.
My plan is to redesign the options menu a bit so more of these values can be exposed and customized.
Gonna close this as it'll be folded into Redesigned Option menu #55 #
