### ISSUE TITLE
Left/right view bob when walking should be user-configurable

### ISSUE THREAD

**Issue by fantasticaneer** [Phazorknight/Cogito#39]
Would appreciate an option by default to configure the viewbob that occurs when you walk / run, it's pretty intense by default!

**Comment by Phazorknight** [comment]
This is already included (though not named that well I admit).

Try tweaking the _Wiggle_ parameters on the player.gd script:

![image](https://github.com/Phazorknight/Cogito/assets/70389309/94026f1e-12f8-424b-95f9-a05a4b931b71)
