### ISSUE TITLE
Wieldable raycast weapon

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#40]
Would you consider a wieldable raycast weapon for the project?
Could this also include recoil?

**Comment by Phazorknight** [comment]
Just added an early version of a wieldable raycast weapon - a laser rifle.
This also spawns rays that linger in the air and then slowly fade out.

**Comment by Phazorknight** [comment]
Still chipping away at general wieldables, but will follow up with that in #5 . As a raycast weapon is now implemented, I'm closing this one.
