### ISSUE TITLE
Crouch walk sound is weirdly loud compared to standard walk / run sound

### ISSUE THREAD

**Issue by fantasticaneer** [Phazorknight/Cogito#41]
Crouch walk sound is quite loud and 'stompy' compared to standard walk sounds

**Comment by ac-arcana** [comment]
This may be due to distance from the sound source - ie the sound is falling off more because you are farther away when standing.

The player script could adjust the volume of the sound when crouching to fix this.

**Comment by ac-arcana** [comment]
I have a pull request in to allow crouch, walk, and sprint footstep volumes to be dynamic.
https://github.com/Phazorknight/Cogito/pull/50

**Comment by Phazorknight** [comment]
> Crouch walk sound is quite loud and 'stompy' compared to standard walk sounds

Yes, this is definitely a legitimate flag.



> This may be due to distance from the sound source - ie the sound is falling off more because you are farther away when standing.
> 
> The player script could adjust the volume of the sound when crouching to fix this.

This is correct, distance to sound source is what makes the volume change.
Thanks to ac-arcana, this can now be adjusted. I've approved the PR and this is now added to main.

See the player.gd script Autio Parameteres to adjust this.
