### ISSUE TITLE
No ability to drop items in the player inventory

### ISSUE THREAD

**Issue by fantasticaneer** [Phazorknight/Cogito#43]
This seems a pretty big deal - once you pick something up it's 'stuck' in your inventory as there's no way to drop it back in the world

**Comment by ac-arcana** [comment]
This is definitely an issue. Currently with the inventory using left and right click for actions, I'm not sure there is a separate action to use for this.

I can think of a couple of ways to support this. One would be to add drag and drop, and when an item is dropped outside of an inventory cell it is dropped on the ground. Another would be to allow a right click context menu on inventory items.

**Comment by Phazorknight** [comment]
Actually there is:

1) Open inventory
2) Pick up item as if you wanna move it to another slot.
3) Right click (default) into the game view/world drops the item back into the world.

If you use gamepad it has a specific assigned button to drop an item.

Closing this.

**Comment by ac-arcana** [comment]
Interesting, I think then the project would benefit from some not in the UI that this is a possible action, as it did not even occur to me to do this with right click. Perhaps PC can have a drop button as well?

**Comment by fantasticaneer** [comment]
> Actually there is:
> 
> 1. Open inventory
> 2. Pick up item as if you wanna move it to another slot.
> 3. Right click (default) into the game view/world drops the item back into the world.
> 
> If you use gamepad it has a specific assigned button to drop an item.
> 
> Closing this.

I appreciate your quick reply and I'm sorry for spamming with issues. I think the lack of clarity about this is a bit of a UI/UX issue-- my initial thoughts are that *right clicking* after dragging out into the game view is weird behavior, I would expect to drop items by dragging out and left clicking, and it would make sense for some sort of icon to appear on the cursor/item, like an arrow, when it is in a spot where you can drop it.

Just my thoughts, obviously as it's meant as a free framework it can be extended by users to add functionality like this, or a dedicated drop key, but it would help for ease of use / UX imo.
