### ISSUE TITLE
Inventory weight

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#44]
Assign weights to inventory items and slow/stop the player when exceeding weight capacity with carried items.

**Comment by Phazorknight** [comment]
This is a game specific design decision, but shouldn't be that hard to implement.
Will consider it in the future but is very low priority.

**Comment by ac-arcana** [comment]
Further to your comment on my other related inventory issue, if the inventory system will be decoupled and easily replaceable with other inventories, then I would suggest this doesn't need to be supported at all and can be closed
