### ISSUE TITLE
Inventory item cell size

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#45]
Support inventory items that take up more than one inventory cell or slot, such as a 2x2 item.

**Comment by Phazorknight** [comment]
Hi,
Unfortunately this feature would go against how the current inventory system is built, so this would require rebuilding it from scratch. Currently I have no plans on doing so, as this is more of a game specific design decision.

I am planning on decoupling the current inventory system a bit more so it'll become easier to replace with your own ones in the future.

**Comment by ac-arcana** [comment]
Decoupling the system to allow other inventories to be used does sound like a great idea.
Perhaps that can be created as an issue and any further inventory related issues can be closed if the current system is intended more as a demo and not to be used in a final product.
