### ISSUE TITLE
Interaction Text location does not transform position properly with resolutions

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#46]
![Screenshot 2024-02-11 161709](https://github.com/Phazorknight/Cogito/assets/57206297/c799dc40-acf6-4324-80d8-d6891feded4b)
![Screenshot 2024-02-11 161810](https://github.com/Phazorknight/Cogito/assets/57206297/f5c80544-ccec-4ed7-a39e-37108e74131a)
As seen in the added screenshots, when the window is maximized, the interactable text shoots way out of where it should be.

**Comment by Phazorknight** [comment]
Yup, thanks for flagging.

There's several UI related issues.
I'm still getting to know how exactly UI in Godot behaves so i'm hoping to improve and make the overall UI more dynamic to adapt to window size.

In the meantime, you can fix this by moving/adjusting the Player_HUD / PromptArea node to your needs.

![image](https://github.com/Phazorknight/Cogito/assets/70389309/3bcf9017-ec72-4c0c-9eda-009d5ae15da5)

**Comment by ac-arcana** [comment]
![image](https://github.com/Phazorknight/Cogito/assets/5461795/70ce685f-cd53-4193-8f9f-306f195eb79f)
Anchor preset -> set to current ratio
This fixed it in my project.

**Comment by Phazorknight** [comment]
Thanks for this, ac-arcana.

I've applied this as a quick fix in 202402.02.
