### ISSUE TITLE
Default input for free look

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#47]
I notice a free look feature with no input set by default. Could these be set to something like caps lock and R stick press?

**Comment by Phazorknight** [comment]
To be honest I don't even know what that does. 😅 
Feel free to add a PR with a new input map action, but this might not be needed at all...?

**Comment by ac-arcana** [comment]
Its a freelook like I've seen in DayZ. Basically, it allows you to run forward while looking around the character. It seems like a nifty feature, I don't see harm in keeping it as an optional feature to be used by devs.

You can bind the input to caps lock for example, and then hold it while running with W. You can look left and right but continue to run in the same direction.

**Comment by Phazorknight** [comment]
Oh, now I get it. Yeah, definitely no harm in keeping that in.

**Comment by Phazorknight** [comment]
Better late than never! Added default key bind for freelook (CapsLock) in https://github.com/Phazorknight/Cogito/commit/fa3b5fa4bc085cf18feb939d6c2b1c3111a97326

Gonna leave the game pad bind for now.
