### ISSUE TITLE
Hold interact to carry

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#48]
Instead of a separate input to carry an item, it could be set to a hold input for the normal interact button. This saves some buttons on controller for other uses.

**Comment by Bezoika** [comment]
I am not affiliated with the project but with all due respect, you are flooding the issues section with suggestions instead of actual problems/bugs, perhaps put these in the Discussions under Ideas.

**Comment by ac-arcana** [comment]
Hi, sorry I'm pretty new and not used to GitHub. I thought this was the
only way to discuss really. I'll happily look up/learn about the feature to
create discussion and prevent issue spam in the future :)

**Comment by Phazorknight** [comment]
I've been thinking something similar.
There is a *HoldInteraction* component that can be added, but ideally I'd like to make this an option for the generic interaction component. The goal would be to apply different actions whether an input map action has been pressed and released or pressed and held a certain amount of time.

My first tries though to get the same button to either trigger one function for a regular press and another function for a press-and-hold haven't been successful yet though.

**Comment by Phazorknight** [comment]
Surprise, had an idea on how to get this to work and just pushed a commit with an early version of a new Interaction Component that should enable this behavior:

**DualInteraction Component**
- Lets you trigger two different interactions with the same input_map_action, depending on if you hold it long enough.
- See the Stamina Extension pickup in the Demo 01 scene as a test example.
- This component doesn't have any interaction logic by itself, instead it sends signals that can be hooked up to other components or anything else.
- To make this compatible with the included interaction components, I had to modify these a bit, should be fully backwards compatible though. Basically you have to "disable" the other interaction components so they won't get triggered by the player inputs (or show up in the HUD as prompts). Instead these components will now get triggered by this new DualInteraction component.
- Hasn't been extensively tested yet, so might have some odd behaviour here and there. Also might not work with all of the current other InteractionComponents yet, also has so far only been tested on Cogito_Objects, not on stuff like doors, switches, buttons, turnwheels etc.

**Comment by ac-arcana** [comment]
This is exciting! I'll try it on my stamina potion / beer bottle in my project

**Comment by ac-arcana** [comment]
I think I'll mark this closed and we'll just create new issues if there are bugs. I'm happy with how this has turned out
