### ISSUE TITLE
Reworking wieldables

### ISSUE THREAD

**Issue by Phazorknight** [Phazorknight/Cogito#5]
As they're currently implemented, Wieldables are pretty cumbersome to manage.
I'm planning on reworking those to make these work more as expected, especially when being wielded/equipped, unequipped, switching between them, etc.

**Comment by Phazorknight** [comment]
Basics of new Wieldable system are in place.
A couple more todos:
- Clean/restructure up how the Wieldables are placed in the Player scene for animation handling.
- Add Reload functionality.
- Polish Wieldable Info HUD area in screen bottom right.

**Comment by Phazorknight** [comment]
Just to update this here:
- Reload functionality is done.
- Still need to clean up Player scene wieldables a bit / make it clearer on how they're setup.

**Comment by paperclipmaximizer** [comment]
What's the progress here? I've been working on implementing a key 'wieldable' and would like to see your changes before I submit a PR

**Comment by Phazorknight** [comment]
Hey, sorry for the radio silence.

This has progressed, just need to clean up a bit more and do a proper documentation.
But here's the summary so you can start working on your own wieldable.
This is also how they're set up in the current latest version 202401.15:

- the pickup of your wieldable can/should be a regular pickup
- the item resource of your wieldable should be assigned to the slot of your pickup.

Now the trickier part:
- Your wieldable model/mesh and their logic need to be attached/a child to a Node under `Player/Neck/Head/Wieldables/`
- The node needs to have the same name as the string name of your wieldable item resource.
- The node also needs to be added to the Wieldables node array of the PlayerInteractionComponent

Finally your wieldable logic needs to contain at least these two functions:
`action_primary(_camera_collision:Vector3, _passed_item_reference:InventoryItemPD)`
`action_secondary(_is_released: bool)`

_camera_collision is used for spawning projectiles if needed. _passed_item_reference is used to update your item resource.
_is_released is used to create behaviour that reacts if the input for action_secondary is being let go (used for aim-down-sights for example)

The Wieldable_Flashlight.gd and WieldablePistol.gd are set up with these, so I can recommend just looking/copying those when you want to setup your own.

**Comment by ac-arcana** [comment]
How about defining the wieldable model/mesh/logic in its own scene. Then in the InventoryItemPD have a variable with contains a string path to the scene. When a wieldable is going to be equipped then instantiate the scene. This would prevent needing to place every single wieldable on the player rig.

**Comment by ac-arcana** [comment]
I have another suggestion for wieldables, instead of using an enum, what about using inheritance? If there was a base wieldable and each other type was inherited I think this would be better OOP, and allow people to create new types

**Comment by Phazorknight** [comment]
Hey everyone,
Wanted to give an update that I'll try to improve this more, so if you're working on your own wieldables, be aware that some changes are coming.

- Wieldable Nodes that are part of the Player tscn will also be turned into tscn's to allow better modularity and maybe even instancing.
- Will try to move Wieldable animations inside of them.
- Making the wieldable actions be controlled by signals to improve decoupling that currently causes bugs and crashes.

**Comment by Phazorknight** [comment]
First bigger steps toward this are now out in update BETA 202402.10.

In regards to using signals, I'm currently not sure how useful this is in practice as the player interaction component has to handle any wieldables pretty directly and usually ever only one at a time.

**Comment by ac-arcana** [comment]
Perhaps as an alternative to signals you could utilize a base class with a class name like Wieldable that had the necessary functions defined in it.
Then to make a new wieldable we can extend Wieldable and implement our own function logic.

**Comment by ac-arcana** [comment]
@Phazorknight, are you still planning more changes to wieldables? I think everything you've listed here is pretty much complete now.

**Comment by Phazorknight** [comment]
Hey, no, haven't really changed anything else as I was working on the Quest system.

If you wanna take another look at it be my quest, I would be keen how to set something like this asset up with Cogito's system to see if there's more stuff to improve: [https://levraicoincoin.itch.io/animated-fps-pistol](https://levraicoincoin.itch.io/animated-fps-pistol)

**Comment by Phazorknight** [comment]
Another update, mostly related to wieldable handling, not too much to the wieldables themselves.
This should reduce unexpected behaviour when swapping/reloading wieldables, as there are now checks in place to stop other actions when swapping or reloading takes place.

**Comment by grgp** [comment]
@Phazorknight Hey thanks for the constant updates! I haven't seen this being suggested yet, but are you also planning to do a melee wieldables? A simple baton or a crowbar would be cool.

I found a reference to melee on the wieldable settings, but I couldn't find anything on the demo scene. Changing the Wieldable Range and Wieldable Damage to a non-zero value also didn't seem to do anything.

I think for starters, just a simple click -> play one animation -> hit would be pretty good already. And then later do something more complex like sword swinging right-to-left-to-right animations, blocks, parries, power attacks. Some of that might be out of scope for this template, though.

I like how [Gloomwood](https://www.youtube.com/watch?v=c1HMCHd3GqA) does it, it looks pretty old-school. And [here](https://www.youtube.com/watch?v=zpTcXky_8yo) are [also](https://www.youtube.com/watch?v=qMBJaVL-vKc&t=1s) some [Godot](https://github.com/catprisbrey/Cats-Godot4-Modular-Souls-like-Template/commits/main/) examples.

**Comment by Phazorknight** [comment]
Holy smokes that Soulslike template is mighty impressive.

And yes, I'm planning to add a simple melee wieldable soon.
My idea would be something like a crowbar that moves a damage area around in front of the player when swung and applies damage to objects inside of it.

>And then later do something more complex like sword swinging right-to-left-to-right animations, blocks, parries, power attacks. Some of that might be out of scope for this template, though.

As this is very game-specific design, I'm not planning on examples for that, but the wieldables are set up in a way that custom behaviour like this should not be too hard to implement. The basic framework to create stuff like blocking or charge attacks is in place.

**Comment by grgp** [comment]
Awesome! Looking forward to it.

And yeah that Soulslike template is crazy. If you go to the author's YouTube [channel](https://www.youtube.com/watch?v=pdhfyducng4), he probably has the most detailed guide and devlog for any Godot template ever.

**Comment by Phazorknight** [comment]
I've just added a new melee wieldable: a Pickaxe.
It uses an Area3D, which has it's monitoring property switched OFF per default.
When swinging, the swing animation turns the monitoring propery ON, thus detecting if it hits any objects with a HitboxComponent. If it does, damage based on the WieldableItem damage is applied.

You can test this by hitting the TargetDestructables in the scene.
Using an Area3D this way should allow pretty good customization about shape and timing.

The pickaxe has currently no secondary option, but if anyone wants to try implementing a block or charged swing or whatever, that's a great spot to experiment.

**Comment by grgp** [comment]
Nice!!! Wow that was quick, thank you so much!
