### ISSUE TITLE
Options Menu Invert Y Toggles V-Sync

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#52]
![image](https://github.com/Phazorknight/Cogito/assets/5461795/ee6de2bc-d239-49f7-bd53-dc5ae7c04b57)

The signal is hooked up to v sync

**Comment by Phazorknight** [comment]
Nice catch, gonna fix that with the next version.

**Comment by Phazorknight** [comment]
Fixed in 202402.02.
