### ISSUE TITLE
Interaction crash when interactions are too close to eachother

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#57]
https://github.com/Phazorknight/Cogito/assets/57206297/d93cc306-35ea-4f8a-abce-0dfa8b830b37

![Screenshot 2024-02-11 215829](https://github.com/Phazorknight/Cogito/assets/57206297/6b90e2c2-1188-478b-81c9-ff3027e4e26f)
![Screenshot 2024-02-11 215854](https://github.com/Phazorknight/Cogito/assets/57206297/b4d9cf85-0339-4c41-8c65-1234225ebc28)

When picking up the battery, it is too close to the drawer, from what i understand its causing the interaction on the drawer to be free'd, so when trying to close the drawer after, it causes a crash.

**Comment by Phazorknight** [comment]
This is odd, so far I wasn't able to reproduce this.
I see you changed the default interact actions, can you confirm which ones you have on the drawer and the battery when this error occurs?

I do know one or two issues with the interaction raycast check that can be improved that might fix this error, so I'll look into that as well.

**Comment by Phazorknight** [comment]
Ok, try the latest commit from main and see if this might fix your issue: https://github.com/Phazorknight/Cogito/commit/e8198c26ad42f419f4637c0e65dc248a80082ca3
