### ISSUE TITLE
Jumping while crouching.

### ISSUE THREAD

**Issue by OtsoT** [Phazorknight/Cogito#59]
Jumping while crouching causes all stamina to be lost due repeated jumps every frame.

**Comment by ac-arcana** [comment]
I also notice that I get footstep sounds repeating, even when standing still, after attempting to jump while crouched.

**Comment by ksjfhor** [comment]
This fixed it for me, could help maybe with #68.

**Comment by ksjfhor** [comment]
Not really fixed, it seems that the jump is somehow still stored.
Jump while in crouching mode, you jump once and stamina gets reduced by 5.
When you just let go of the crouch_button the player will strangely jump again.
