### ISSUE TITLE
Hold interaction range cancel

### ISSUE THREAD

**Issue by OtsoT** [Phazorknight/Cogito#60]
When doing the 'hold X seconds to activate' interaction (like in the demo drawbridge) you can still move clearly out of range.
Had fun flinging myself in the air using the drawbridge. :airplane:

**Comment by Phazorknight** [comment]
Big oof.
Shouldn't be too hard to fix, will look into it.

**Comment by Phazorknight** [comment]
Added the following in 202402.04:

HoldInteraction now checks for *interaction_distance*: If the player is further away from the object than the InteractionRaycast length, the hold gets interrupted.
Designing your HoldInteractions with this in mind should prevent any odd behaviour. I've also set the collision layer of the box behind the TurnWheel to block the interaction raycast, so it should be a bit trickier to play human catapult.
