### ISSUE TITLE
Infinite physics carry.

### ISSUE THREAD

**Issue by OtsoT** [Phazorknight/Cogito#61]
When holding physics item (like the box in the demo) you can trap it behind a wall and walk away while technically still carrying it. This should have some sort of forced drop at some distance.

**Comment by Phazorknight** [comment]
Makes total sense and shouldn't be too hard to implement. Will try to get that added soon.

**Comment by Phazorknight** [comment]
Added the following in 202402.04:
CarryableComponent now has a *drop_distance* property.
If the distance between object and the carryable position goes above this value, the object gets dropped.
It's not perfect but helps with "sticky objects".

As a fun side-effect, if the carrying_velocity_multiplier can't keep up with how much the player moves around with the mouse, the drop_distance is easily reached, thus making it feel like you can actually physically throw objects.

Tweaking these properties is definitely recommended to achieve desired behaviour.
