### ISSUE TITLE
New surface material footstep system crashes on collisions with ArrayMesh

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#65]
I use qodot for my level building which uses an ArrayMesh for every level build. The second I try to move it causes a crash with the new system. I noticed it works fine on the demo scene so I'm assuming based on the information that it is only looking for normal MeshInstances.
![image](https://github.com/Phazorknight/Cogito/assets/57206297/5144213f-7333-4b8f-bb06-82bf3e72f6d4)

**Comment by ac-arcana** [comment]
I'll look at this ASAP. I love Qodot myself and intend to use it later. An array mesh is something I had not considered.

Also, regarding Qodot, what are your thoughts on how to support footstep materials through Trenchbroom?

**Comment by Bezoika** [comment]
All good, no rush, I took a look at the system a bit when i got the crash. Looks like a cool way of implementing it.

> Also, regarding Qodot, what are your thoughts on how to support footstep materials through Trenchbroom?
This really shouldn't be too much of an issue, as if you add a .tres with the same name as the texture that trenchbroom uses, it will automatically replace the texture with the material when the map is built in godot. Add said material into the step system and it should work fine.

**Comment by ac-arcana** [comment]
You're definitely right this is due to an array mesh. I'm able to prevent the crash and tell when it is an array mesh with the following:

`func _get_surface_material(collider : Node3D) -> Material:
	if collider is CSGShape3D:
		return collider.material
	elif collider is StaticBody3D or collider is RigidBody3D:
		#find all children of the collider static body that are of type "MeshInstance3D"
		#if there are multiple materials, just default to the first one found
		var mesh_instances = collider.find_children("", "MeshInstance3D")
		if mesh_instances:
			if mesh_instances[0].mesh:
				if mesh_instances[0].mesh is ArrayMesh:
					print("array mesh")
					print(mesh_instances[0].mesh.surface[0])
				else:
					return mesh_instances[0].mesh.material
	return null`

No idea how to get the right materials from an array mesh yet though.

**Comment by ac-arcana** [comment]
I'm not sure that getting the right material is going to be possible. Currently, I'm just getting the first material I can find from a collider. This works fine for small models, but when the entire map is one static body this poses a problem. 

Since I am relying on collision data, what I am getting back is the static body. From there I find the array mesh. The trouble is polling an array mesh to find out what surface would be at the collision location and its material. This is beyond my expertise and I'm not sure that its possible. I don't really know how to go about trying to solve it.

I can provide an update to fix the crash and just play a generic sound instead for now.

**Comment by ac-arcana** [comment]
I'll def take a look, and I will do some more digging into docs to find some kind of alternative at least. I'm determined to use Trenchbroom

**Comment by ac-arcana** [comment]
I got to look at the video now. It looks like it might work, I'll definitely dive deeper into the technique he used and try it out. It's gonna take a bit of time for me to really dive in though. It's a very busy week for me and next week I'll be away on a trip.

**Comment by Bezoika** [comment]
All good man, love to find it when it works but I'm in no rush, busy here too.
