### ISSUE TITLE
Equipped Stuff let it crash on transition, non-equipped works

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#66]
Hey, 

in the current Version BETA 202402.04 I found something.

When you have something equipped, like the flashlight or the foam gun, and then move into the transition zone, it crashes with "Invalid call. Nonexistent function 'unequip' in base 'Nil'".
When you have nothing equpped it works and you get teleported to the other scene.

It stops on the PlayerInteractionComponent.gd line 161: equipped_wieldable_node.unequip()

I am not sure on how to fix this...

**Comment by Phazorknight** [comment]
Hey, sorry about this, and thanks for flagging this, this is a pretty new bug.

I can try to attempt a quick fix, but as I'm trying to rework the wieldables a bit (see #5 ), this might take a bit longer.

**Comment by ksjfhor** [comment]
Hey, no need to be sorry, take your time :)

**Comment by Phazorknight** [comment]
This should be fixed in _BETA 202402.10_
This is a bigger update so you might wanna backup your project.
