### ISSUE TITLE
Suddenly Hazard Zone

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#67]
Hi,

I am not sure on how I am doing it. But I can replicate it.

When I was in the LightZone and then got into the Hazard Zone, then I get out of the Hazard Zone and suddenly I get the visual hint that I am in the Hazard Zone and my HP gets drained, but I am not in the Zone.
Please see the video attachment if you don't know what I mean. 

https://github.com/Phazorknight/Cogito/assets/87974401/6d391449-436f-471e-a028-401d7e3ae124

https://www.veed.io/view/31afa1c4-a564-4a8d-922b-7f9016d32112?panel= (githubs 10 MB border is a little pain for me)

**Comment by Phazorknight** [comment]
Oh, thanks for flagging this. Will take a look.

**Comment by Bezoika** [comment]
I think this is just damage from Sanity right? Once you walk into the lightzone it sets brightness level to 1 and then when you walk out it sets it to 0, after a limited amount of time you start taking damage.

**Comment by ksjfhor** [comment]
> I am not sure on how I am doing it. But I can replicate it.

Bezoika is right, when I get into the lightzone and just wait I get the same result. So it was just my stupidity, sorry to bother you.
I got confused because I was in the HazardZone just in the right time.

**Comment by Phazorknight** [comment]
Re-opening this so I'll look into this more:
Need to make it clear that this is happening due to the SanityComponent, as it's otherwise very confusing. Will update once I fix that.

**Comment by ksjfhor** [comment]
I would suggest to make it visibily more clear that something other then the hazardzone is happening, like with a black overlay instead of the same (?) red of the hazardzone. Some more debug prints like "insanity now active" could also help to reduce the confusion, at least for me :)

**Comment by Phazorknight** [comment]
Should be improved with https://github.com/Phazorknight/Cogito/commit/a117370610f000ae11005e84e01ad0c0ad12237c:
I've added a bool flag to the player.gd to easily turn sanity off.
Also added a print that tells you if the player is losing health due to low sanity.

All of this will be improved in the future when tackling #49, but for now I consider this closed.
