### ISSUE TITLE
A few unexpected things

### ISSUE THREAD

**Issue by generrosity** [Phazorknight/Cogito#71]
Hello!

I've noticed a few more unusual things. If you've seen them all, feel free to close this :)

- If you hover over a item in the world, TAB to open inventory, you can still use "F" to pick up the item. This might be intentional, but it feels like quick-slot and pickup keys should both be disabled.
![image](https://github.com/Phazorknight/Cogito/assets/12838061/9a944b67-995a-4a71-9f13-90848fbf4eb1)

- I hit ESC so much 🤣 
  -  Could ESC close inventory view, please?
  - When entering Reading mode, could the "press F to read" vanish, and "press F to stop reading" be added to the Reading box? Could ESC close out of reading too, please? Should I be able to open inventory while reading? If you walk away from the paper, you can't close the read panel 😟
![image](https://github.com/Phazorknight/Cogito/assets/12838061/b5c3d47c-0cca-4695-9be4-9afe74d58594)

- On opening inventory, the second item slow is highlighted as if it is highlighted over. When I open the chest, it flickers to the second inventory slot before picking up or putting an item down. At a guess, a mouse-down event held down will highlight the second, while when the click comes up or completes the action works correctly.

Love your work :)

**Comment by Phazorknight** [comment]
Ok, quite a few of those issues are now fixed. These aren't yet:

- Player can still interact with the world while inventory is open. Will look into deactivating this as it could potentially cause other issues.
- Second slot highlighted on opening inventory: This is currently an issue with how the inventory UI gets instanced. As it's not breaking anything I haven't looked into it further yet.

> If you walk away from the paper, you can't close the read panel

You should not be able to move while the reading panel is open. Can you confirm this is still happening and how to reproduce it?

**Comment by generrosity** [comment]
Excellent!

I'll retest tomorrow night at this stage.

**Comment by generrosity** [comment]
Things are looking great! All of the prompts vanish at the right time, ESC just works everywhere. Fantastic!

I can't walk away from the note, so that is great too.

**Comment by Phazorknight** [comment]
> Player can still interact with the world while inventory is open. Will look into deactivating this as it could potentially cause other issues.

The latest updates to the interaction component enables devs to control this behaviour (ie. letting players interact with an object while a GUI is open or not).

Thus I consider this issue as closed.
