### ISSUE TITLE
Item (battery) Stack set to 5, can increase by 1 in the inventory

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#73]
Hi, in the current main version:
When I pick up 7 batterys I get 5 in the first slot and 2 in the second slot. So far so correct.
But when I open the inventory, pick up the 2 from the second slot and right click on the first slot:
![grafik](https://github.com/Phazorknight/Cogito/assets/87974401/5368d43f-3bef-40ae-897d-f8122597b100)
This 'only' gets the stack size +1, an +2 could I not provoke.

**Comment by Phazorknight** [comment]
Found the culprit, should be fixed in https://github.com/Phazorknight/Cogito/commit/075c9028ff4a4fd13a214e9b4bf016412baeb915

Considering this closed.
