### ISSUE TITLE
Compatibility with Trenchbroom/Qodot?

### ISSUE THREAD

**Issue by JouBqa** [Phazorknight/Cogito#77]
When I step on ground made in Trenchbroom and brought into Godot with the Qodot plugin I get this error:

Invalid get index 'material' (on base: 'ArrayMesh').
![image](https://github.com/Phazorknight/Cogito/assets/78951590/06e16e27-fbbf-4c06-b3fb-e517c55379c1)
![image](https://github.com/Phazorknight/Cogito/assets/78951590/58e2037b-dfc5-48fe-afc1-e605ad63d4be)

**Comment by FailSpy** [comment]
You may want to pull the latest version of the main branch. 
This should be solved by #70 , but looking at your screenshot there and your errors, you don't have the latest version of `footstep_surface_detector.gd`: https://github.com/Phazorknight/Cogito/blob/075c9028ff4a4fd13a214e9b4bf016412baeb915/COGITO/DynamicFootstepSystem/Scripts/footstep_surface_detector.gd#L63

Do let me know how it functions for Trenchbroom/Qodot, as I'll be very keen to have it working with them!

**Comment by FailSpy** [comment]
Looks like this can be closed after no updates? @Phazorknight

**Comment by Phazorknight** [comment]
Great, closing.
