### ISSUE TITLE
Crouch jumping broken, or intentional ?

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#79]
Hi, 
when you have crouch_jumping active (like the standard when opening up the project).
Do the crouch jumping but let go of the crouch_button ("c"), shortly after jumping ("space") you gain height to nearly the point where you would regulary land when you jump.

Is this intended ?
For me it looks like the JumpCoolDownTimer is not working.

https://github.com/Phazorknight/Cogito/assets/87974401/a589c0b7-ec9b-4f90-9ff4-170da9eb989a

At first I just crouched and jumped for you to see a marking with the target, otherwise it would be hard to see / recognize if not played by yourself.

**Comment by Phazorknight** [comment]
Will take a look myself but from your video this looks to me as working as intended.
Crouch-jumping aka duck-jumping has been a staple in quite a few games, and I think the first person controller was explicitly made to support it.

I think the jump cooldown timer is only used to avoid retriggering jumps on bad collisions.

**Comment by FailSpy** [comment]
@Phazorknight I have a branch I'm working on to address the visual jitter as well as some improvements for slide jumping

**Comment by FailSpy** [comment]
I would say this is very much intentional. I tried to make jumping consistent for crouch jumps and regular jumps by saying that you wind up with the players feet off the ground by exactly the same amount

**Comment by ksjfhor** [comment]
Ty both. I was not sure as it felt not right for me, I am looking forward for the [PR#82 ](https://github.com/Phazorknight/Cogito/pull/82) :)

**Comment by Phazorknight** [comment]
Considering this solved with the merge from #82 / https://github.com/Phazorknight/Cogito/commit/001c48f0dbab6cb4a2450c5d8e988fdb341c893b.
