### ISSUE TITLE
Scalable UI for full screen

### ISSUE THREAD

**Issue by cmr624** [Phazorknight/Cogito#81]
Is it possible to make the UI elements scaleable, so it remains its same size as in the default viewport (not full screen), when scaled up? the options menu, and hotbar are pretty unusable at full screen. 

I'm new to Godot and not sure how to achieve this with the UI system - or if an issue here is an appropriate place to ask about this - but wondering what should the approach be for this project? Thanks!!

**Comment by cmr624** [comment]
Would love to help or learn as you work, when you are working on this. let me know if there are any resources you find?

**Comment by grgp** [comment]
Hey I'm trying to implement this feature here, please take a look!
https://github.com/Phazorknight/Cogito/pull/90

**Comment by Phazorknight** [comment]
Basic UI scaling is implemented, so I'm going to close this.
