### ISSUE TITLE
Current Version won't start

### ISSUE THREAD

**Issue by ksjfhor** [Phazorknight/Cogito#83]
Hi, in the current master version:

when I start the project it crashes with: 
"Parser Error: Cannot find member "fullscreen_kay_name" in base "OptionsConstants""

When I comment out the lines 50, 66 and 75 in the options_menu_controller.gd it will start.

It may be the options_constants.gd missing `const fullscreen_key_name = "fullscreen_mode"`.
See https://github.com/Phazorknight/Cogito/commit/e923d40175f08ec1cbb19ab10a44c7569d624278, since I am still not able to cherry pick, be it my own stupidity or github ...

**Comment by Phazorknight** [comment]
That's odd, I've updated the OptionsConstants on my end and they should've been included in the commit. Will look into it.

Fullscreen_key_name is deprecated. Was replaced with windowmode_key_name.

**Comment by FailSpy** [comment]
If `fullscreen_key_name` is deprecated @Phazorknight, then it's possible that you *have* updated OptionsConstants, but rather the file [options_menu.gd](https://github.com/Phazorknight/Cogito/tree/main/COGITO/EasyMenus/Scripts/options_menu_controller.gd) wasn't included in your commit, as that file still references `fullscreen_key_name`:

https://github.com/Phazorknight/Cogito/blob/901a2bef817bbcfbc5e3b3d3ef35568b14e53145/COGITO/EasyMenus/Scripts/options_menu_controller.gd#L50
https://github.com/Phazorknight/Cogito/blob/901a2bef817bbcfbc5e3b3d3ef35568b14e53145/COGITO/EasyMenus/Scripts/options_menu_controller.gd#L66

**Comment by Phazorknight** [comment]
Edit: Just saw your comment.

Sorry, yeah, updating the options constants for the new menu in turn broke the old menu and any of it's references, which includes the PauseMenu scene and the MainMenu scene.

Will update those to use the new Options, which will fully deprecated the old one, so prepare for that. Will try to get this done today.

**Comment by Phazorknight** [comment]
Okay, I've just released a quick fix for this in https://github.com/Phazorknight/Cogito/commit/c328226998c00f9a0672b9e6dd61e95c9cc8e720

This basically removes any references to the old options menu / PauseMenu in the current demo scenes and MainMenu scene.

I'm considering this specific issue closed, but will continue to properly deprecate/remove the old options and update in this thread: #55
