### ISSUE TITLE
Toy Pistol no longer appearing in hand after latest update.

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#87]
There's no errors and it still shoots but there is no visual mesh.

**Comment by Phazorknight** [comment]
Wasn't able to reproduce this on my end.
 But I found a different error related to how actions are triggered with the wiedlables, so will push a new commit shortly.

**Comment by Bezoika** [comment]
Not sure what i did as I didnt actually change the original pistol scene but replacing the toy gun scene with the git version fixed it. I was attempting to create a new gun but I'm having a difficult time. Made every individual piece as far as I know, am able to pick it up, but it fails to show the mesh or shoot.

**Comment by Phazorknight** [comment]
Did you create a unique script for your new custom wieldable?
There's no custom class for this yet in Cogito, so copy-pasting either the flashlight or the toy pistol is probably your best starting point at this point.
Then of course double-checking all your references and seeing what log prints you get would help troubleshooting this.

That being said, I'm hoping to start recording more proper tutorials soon and wieldables are on top of the list.

**Comment by Bezoika** [comment]
No unique script, tried making a replica of the toy pistol, I think i got all the references but its a little difficult when you don't know how everything is connected, a tutorial would be absolutely amazing.

**Comment by Phazorknight** [comment]
Going to close this as there's been some updates to the Wieldable system and I've also created a new video overview that hopefully helps.

Feel free to open a new issue if you encounter problems.
