### ISSUE TITLE
Scene Transition Crash

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#93]
I'm just getting back into things and taking a look at all the latest updates. There is so much awesome new stuff!

I noticed if I go to the scene transition on the latest version it is crashing immediately on line 164 of the scene manager.

**Comment by Phazorknight** [comment]
Hm... wasn't able to reproduce that on my end, but line 164 is during loading of scene states.

Can you try deleting all of your currently present scene state files and try again? They might've become incompatible with the recent updates...

**Comment by ac-arcana** [comment]
You are absolutely correct, sorry for the false report. I didn't even know where these files existed until looking into this, lol. I have so much to learn about godot still.

**Comment by Phazorknight** [comment]
No worries.
This is Cogito specific and it's not very well documented yet. I'm planning on rewriting the doc from scratch as well as doing a short video tutorial that goes over how scene management as well as persistence as well as saving and loading is set up.
